import { spotlightItemSchema, type SpotlightItem } from "./schemas";

/**
 * Destaques do catálogo (atalhos e novidades do produto).
 * A escola acrescenta notas próprias em Definições → Destaques (`extras` em school_settings).
 * `link.type`: internal (rota SIGA) | external (URL) | settings (painel de Definições).
 */
const rawSpotlights: SpotlightItem[] = [
  {
    id: "relatorios",
    kind: "function",
    enabled: true,
    order: 10,
    title: "Relatórios avançados",
    body: "Consulte os painéis financeiros e académicos já disponíveis.",
    cta: "Abrir relatórios",
    icon: "rocket",
    tone: "primary",
    accessPath: "/relatorios/academicos",
    link: {
      type: "internal",
      to: "/relatorios/financeiros",
      fallbackTo: "/relatorios/academicos",
    },
  },
  {
    id: "avaliacao",
    kind: "feature",
    enabled: true,
    order: 20,
    title: "Centro de avaliação",
    body: "Lance notas, imprima a pauta oficial e copie o trimestre anterior.",
    cta: "Abrir pedagógica",
    icon: "sparkles",
    tone: "info",
    accessPath: "/pedagogica",
    link: { type: "internal", to: "/pedagogica" },
  },
  {
    id: "matricula",
    kind: "promo",
    enabled: true,
    order: 30,
    title: "Campanha de matrícula",
    body: "Partilhe o link público e confirme candidaturas sem sair do SIGA.",
    cta: "Gerir campanha",
    icon: "school",
    tone: "success",
    roles: ["Administrador", "Secretaria"],
    link: { type: "settings", panel: "matricula" },
  },
  {
    id: "tesouraria",
    kind: "function",
    enabled: true,
    order: 40,
    title: "Cobrança em Kz",
    body: "Faturas, Multicaixa Express e recibos com IBAN da escola.",
    cta: "Abrir faturas",
    icon: "payments",
    tone: "warning",
    accessPath: "/faturas",
    link: { type: "internal", to: "/faturas" },
  },
  {
    id: "calendario",
    kind: "note",
    enabled: true,
    order: 50,
    title: "Calendário no telemóvel",
    body: "Sincronize períodos lectivos com Google Calendar ou o iPhone.",
    cta: "Ver calendário",
    icon: "smartphone",
    tone: "info",
    accessPath: "/calendario",
    link: { type: "internal", to: "/calendario" },
  },
  {
    id: "documentos",
    kind: "feature",
    enabled: true,
    order: 60,
    title: "Modelos oficiais",
    body: "Boletins, declarações e talões no papel da escola.",
    cta: "Abrir documentos",
    icon: "document",
    tone: "primary",
    accessPath: "/documentos",
    link: { type: "internal", to: "/documentos" },
  },
  {
    id: "comunicados",
    kind: "note",
    enabled: true,
    order: 70,
    title: "Avisos à comunidade",
    body: "Publique comunicados e partilhe por WhatsApp ou e-mail Resend.",
    cta: "Abrir comunicações",
    icon: "campaign",
    tone: "success",
    accessPath: "/comunicacoes",
    link: { type: "internal", to: "/comunicacoes" },
  },
  {
    id: "agt",
    kind: "promo",
    enabled: true,
    order: 80,
    title: "Portal AGT",
    body: "Consulte o NIF da escola no Portal do Contribuinte.",
    cta: "Abrir portal",
    icon: "agt",
    tone: "warning",
    roles: ["Administrador", "Tesouraria", "Secretaria"],
    link: { type: "external", href: "https://portaldocontribuinte.minfin.gov.ao/" },
  },
];

export const spotlightCatalog: SpotlightItem[] = rawSpotlights.map((item) =>
  spotlightItemSchema.parse(item),
);
