import {
  BadgeCheck,
  Bell,
  BookOpen,
  CalendarDays,
  ClipboardList,
  FileBadge,
  GraduationCap,
  Home,
  Landmark,
  Link2,
  Mail,
  Megaphone,
  Rocket,
  Smartphone,
  Sparkles,
  Star,
  Users,
  Wallet,
  WandSparkles,
  type LucideIcon,
} from "lucide-react";

/** Nomes estáveis para o catálogo e o selector em Definições. */
export const spotlightIcons: Record<string, LucideIcon> = {
  rocket: Rocket,
  sparkles: Sparkles,
  wand: WandSparkles,
  school: GraduationCap,
  payments: Wallet,
  event: CalendarDays,
  document: FileBadge,
  campaign: Megaphone,
  verified: BadgeCheck,
  smartphone: Smartphone,
  agt: Landmark,
  book: BookOpen,
  users: Users,
  link: Link2,
  star: Star,
  bell: Bell,
  clipboard: ClipboardList,
  home: Home,
  mail: Mail,
};

export const spotlightIconLabels: Record<string, string> = {
  rocket: "Foguete",
  sparkles: "Brilho",
  wand: "Varinha",
  school: "Escola",
  payments: "Pagamentos",
  event: "Calendário",
  document: "Documento",
  campaign: "Comunicado",
  verified: "Verificado",
  smartphone: "Telemóvel",
  agt: "AGT",
  book: "Livro",
  users: "Pessoas",
  link: "Ligação",
  star: "Estrela",
  bell: "Sino",
  clipboard: "Lista",
  home: "Início",
  mail: "E-mail",
};

export function spotlightIcon(name: string): LucideIcon {
  return spotlightIcons[name] ?? Sparkles;
}
