import { describe, expect, it } from "vitest";
import { validateSaftAoXml } from "@/features/finance/saft-validator";
import { buildSaftAoXml } from "@/features/finance/saft-generator";

describe("saft-validator", () => {
  it("should fail validation on empty or malformed XML", () => {
    const res = validateSaftAoXml("");
    expect(res.valid).toBe(false);
    expect(res.errors[0]?.code).toBe("EMPTY_XML");

    const res2 = validateSaftAoXml("<random>test</random>");
    expect(res2.valid).toBe(false);
    expect(res2.errors.some((e) => e.code === "INVALID_ROOT")).toBe(true);
  });

  it("should validate XML generated by buildSaftAoXml successfully", () => {
    const validXml = buildSaftAoXml(
      {
        name: "Colégio Teste Luanda",
        nif: "5000123456",
        address: "Maianga, Luanda",
        city: "Luanda",
      },
      [
        {
          id: "inv-1",
          invoiceNo: "FT 2026/1",
          invoiceType: "FT",
          date: "2026-03-01",
          customerName: "Consumidor Final",
          customerNif: "999999999",
          studentId: "st-1",
          description: "Mensalidade Março",
          amount: 25000,
          status: "N",
        },
      ],
      {
        fiscalYear: 2026,
        softwareCertificateNumber: "000/AGT/2026",
      },
    );

    const result = validateSaftAoXml(validXml);
    expect(result.valid).toBe(true);
    expect(result.errors).toEqual([]);
    expect(result.version).toBe("1.01_01");
    expect(result.companyName).toBe("Colégio Teste Luanda");
    expect(result.totalInvoices).toBe(1);
    expect(result.totalLines).toBe(1);
    expect(result.grossTotal).toBe(25000);
  });

  it("should catch missing NIF and invoice count mismatches", () => {
    const invalidXml = `<?xml version="1.0" encoding="UTF-8"?>
<AuditFile xmlns="urn:OECD:StandardAuditFile-Tax:AO_1.01_01">
  <Header>
    <AuditFileVersion>1.01_01</AuditFileVersion>
    <CompanyName>Escola Sem NIF</CompanyName>
    <FiscalYear>2026</FiscalYear>
  </Header>
  <SourceDocuments>
    <SalesInvoices>
      <NumberOfEntries>2</NumberOfEntries>
      <Invoice>
        <InvoiceNo>FT 2026/1</InvoiceNo>
        <InvoiceDate>2026-01-10</InvoiceDate>
      </Invoice>
    </SalesInvoices>
  </SourceDocuments>
</AuditFile>`;

    const result = validateSaftAoXml(invalidXml);
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.code === "MISSING_NIF")).toBe(true);
    expect(result.errors.some((e) => e.code === "INVOICE_COUNT_MISMATCH")).toBe(true);
  });

  it("should validate Payments section accurately", () => {
    const validXmlWithPayments = buildSaftAoXml(
      {
        name: "Complexo Escolar SIGA",
        nif: "5000123456",
        address: "Luanda",
        city: "Luanda",
      },
      [
        {
          id: "inv-1",
          invoiceNo: "FT 2026/1",
          invoiceType: "FT",
          date: "2026-04-01",
          customerName: "Ana Maria",
          customerNif: "005123456LA012",
          description: "Propina Abril",
          amount: 30000,
          status: "N",
        },
      ],
      {
        fiscalYear: 2026,
      },
      [
        {
          id: "pay-1",
          paymentRefNo: "RG 2026/1",
          paymentType: "RG",
          date: "2026-04-01",
          customerName: "Ana Maria",
          customerNif: "005123456LA012",
          description: "Recibo de Propina Abril",
          amount: 30000,
          sourceInvoiceNo: "FT 2026/1",
          status: "N",
        },
      ],
    );

    const result = validateSaftAoXml(validXmlWithPayments);
    expect(result.valid).toBe(true);
    expect(result.totalInvoices).toBe(1);
    expect(result.totalPayments).toBe(1);
    expect(result.grossPaymentsTotal).toBe(30000);
  });

  it("ficheiro com faturas e recibos (um anulado) passa na verificação de estrutura", () => {
    const xml = buildSaftAoXml(
      { nif: "5417001234", name: "Escola", address: "Rua 1", city: "Luanda" },
      [
        {
          id: "i1",
          invoiceNo: "FT 2026/0001",
          invoiceType: "FT",
          date: "2026-02-01",
          customerName: "Ana",
          description: "Propina",
          amount: 1000,
          status: "N",
        },
      ],
      { fiscalYear: 2026 },
      [
        {
          id: "r1",
          paymentRefNo: "RG 2026/0001",
          paymentType: "RG",
          date: "2026-02-03",
          customerName: "Ana",
          amount: 1000,
          sourceInvoiceNo: "FT 2026/0001",
          sourceInvoiceDate: "2026-02-01",
          status: "N",
        },
        {
          id: "r2",
          paymentRefNo: "RG 2026/0002",
          paymentType: "RG",
          date: "2026-02-04",
          customerName: "Ana",
          amount: 500,
          status: "A",
          statusDate: "2026-02-05",
        },
      ],
    );
    const res = validateSaftAoXml(xml);
    expect(res.errors).toEqual([]);
    expect(res.valid).toBe(true);
    expect(res.totalPayments).toBe(2);
  });
});
