/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcessosRouteImport } from './routes/acessos'
import { Route as AlterarSenhaRouteImport } from './routes/alterar-senha'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as ArquivosRouteImport } from './routes/arquivos'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CatracasRouteImport } from './routes/catracas'
import { Route as ComunicacoesRouteImport } from './routes/comunicacoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CriarEscolaRouteImport } from './routes/criar-escola'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as FaturasRouteImport } from './routes/faturas'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as PedagogicaRouteImport } from './routes/pedagogica'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanosAulaRouteImport } from './routes/planos-aula'
import { Route as SaasAdminRouteImport } from './routes/saas-admin'
import { Route as AlumniAlumniIdRouteImport } from './routes/alumni.$alumniId'
import { Route as AlumniCalendarRouteImport } from './routes/alumni.calendar'
import { Route as AlumniCommunicationsRouteImport } from './routes/alumni.communications'
import { Route as AlumniDocumentsRouteImport } from './routes/alumni.documents'
import { Route as AlumniInsightsRouteImport } from './routes/alumni.insights'
import { Route as AlumniMatchingRouteImport } from './routes/alumni.matching'
import { Route as AlumniOperationsRouteImport } from './routes/alumni.operations'
import { Route as AlumniPipelineRouteImport } from './routes/alumni.pipeline'
import { Route as AlumniPortalRouteImport } from './routes/alumni.portal'
import { Route as AlunosIndexRouteImport } from './routes/alunos/index'
import { Route as AlunosStudentIdRouteImport } from './routes/alunos/$studentId'
import { Route as AuthEmailChangeRouteImport } from './routes/auth.email-change'
import { Route as AuthMagicLinkRouteImport } from './routes/auth.magic-link'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as CalendarioIcsRouteImport } from './routes/calendario.ics'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as FinanceiroRhRouteImport } from './routes/financeiro.rh'
import { Route as MatriculaSlugRouteImport } from './routes/matricula/$slug'
import { Route as PessoasIndexRouteImport } from './routes/pessoas/index'
import { Route as ProfessorPresencaRouteImport } from './routes/professor.presenca'
import { Route as ProfessoresTeacherIdRouteImport } from './routes/professores/$teacherId'
import { Route as RelatoriosAcademicosRouteImport } from './routes/relatorios.academicos'
import { Route as RelatoriosFinanceirosRouteImport } from './routes/relatorios.financeiros'
import { Route as AlumniAlumniIdPortfolioRouteImport } from './routes/alumni.$alumniId.portfolio'
import { Route as AlumniPortalPortfolioRouteImport } from './routes/alumni.portal.portfolio'
import { Route as ApiCalendarIcsRouteImport } from './routes/api/calendar.ics'
import { Route as ApiCatracasDeviceScanRouteImport } from './routes/api/catracas/device-scan'
import { Route as ApiSaasAuditLogsRouteImport } from './routes/api/saas/audit-logs'
import { Route as ApiSaasDomainsRouteImport } from './routes/api/saas/domains'
import { Route as ApiSaasGatewayWebhooksRouteImport } from './routes/api/saas/gateway-webhooks'
import { Route as ApiSaasMailboxesRouteImport } from './routes/api/saas/mailboxes'
import { Route as ApiSaasMeRouteImport } from './routes/api/saas/me'
import { Route as ApiSaasPlansRouteImport } from './routes/api/saas/plans'
import { Route as ApiSaasPlatformAdminsRouteImport } from './routes/api/saas/platform-admins'
import { Route as ApiSaasSignupRouteImport } from './routes/api/saas/signup'
import { Route as ApiSaasStatsRouteImport } from './routes/api/saas/stats'
import { Route as ApiSaasSubscriptionsRouteImport } from './routes/api/saas/subscriptions'
import { Route as ApiSaasTenantsRouteImport } from './routes/api/saas/tenants'
import { Route as ApiWebhooksTwilioSmsRouteImport } from './routes/api/webhooks/twilio-sms'
import { Route as ApiWebhooksWhatsappStatusRouteImport } from './routes/api/webhooks/whatsapp-status'
import { Route as FinanceiroRhFaltasRouteImport } from './routes/financeiro.rh.faltas'
import { Route as FinanceiroRhFolhaRouteImport } from './routes/financeiro.rh.folha'
import { Route as FinanceiroRhPagamentosRouteImport } from './routes/financeiro.rh.pagamentos'
import { Route as FinanceiroRhPresencaRouteImport } from './routes/financeiro.rh.presenca'
import { Route as FinanceiroRhSalariosRouteImport } from './routes/financeiro.rh.salarios'
import { Route as AlumniPortalPortfolioEducationRouteImport } from './routes/alumni.portal.portfolio.education'
import { Route as AlumniPortalPortfolioPrintRouteImport } from './routes/alumni.portal.portfolio.print'
import { Route as AlumniPortalPortfolioShowcaseRouteImport } from './routes/alumni.portal.portfolio.showcase'
import { Route as ApiFinanceGatewayConfirmRouteImport } from './routes/api/finance/gateway.confirm'
import { Route as ApiFinancePayflowSettlementRouteImport } from './routes/api/finance/payflow.settlement'
import { Route as ApiIntegrationsResendWebhookRouteImport } from './routes/api/integrations/resend.webhook'
import { Route as ApiIntegrationsZoomCallbackRouteImport } from './routes/api/integrations/zoom/callback'
import { Route as ApiSaasDomainsCheckRouteImport } from './routes/api/saas/domains.check'
import { Route as ApiSaasDomainsPollRouteImport } from './routes/api/saas/domains.poll'
import { Route as ApiSaasDomainsStatusRouteImport } from './routes/api/saas/domains.status'
import { Route as ApiSaasDomainsVerifyRouteImport } from './routes/api/saas/domains.verify'
import { Route as ApiSaasEmailRoutesRouteImport } from './routes/api/saas/email.routes'
import { Route as ApiSaasPlatformAdminsRevokeRouteImport } from './routes/api/saas/platform-admins.revoke'
import { Route as ApiSaasSubscriptionsBackfillRouteImport } from './routes/api/saas/subscriptions.backfill'
import { Route as ApiSaasTenantsLookupRouteImport } from './routes/api/saas/tenants.lookup'
import { Route as ApiSaasTenantsStatusRouteImport } from './routes/api/saas/tenants.status'
import { Route as ApiSaasTenantsSubscriptionRouteImport } from './routes/api/saas/tenants.subscription'
import { Route as ApiSaasUsageSyncRouteImport } from './routes/api/saas/usage.sync'
import { Route as ApiFinanceGatewayUnitelConfirmRouteImport } from './routes/api/finance/gateway.unitel.confirm'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessosRoute = AcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaRoute = AlterarSenhaRouteImport.update({
  id: '/alterar-senha',
  path: '/alterar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivosRoute = ArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CatracasRoute = CatracasRouteImport.update({
  id: '/catracas',
  path: '/catracas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacoesRoute = ComunicacoesRouteImport.update({
  id: '/comunicacoes',
  path: '/comunicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarEscolaRoute = CriarEscolaRouteImport.update({
  id: '/criar-escola',
  path: '/criar-escola',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaturasRoute = FaturasRouteImport.update({
  id: '/faturas',
  path: '/faturas',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const PedagogicaRoute = PedagogicaRouteImport.update({
  id: '/pedagogica',
  path: '/pedagogica',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosAulaRoute = PlanosAulaRouteImport.update({
  id: '/planos-aula',
  path: '/planos-aula',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasAdminRoute = SaasAdminRouteImport.update({
  id: '/saas-admin',
  path: '/saas-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniAlumniIdRoute = AlumniAlumniIdRouteImport.update({
  id: '/$alumniId',
  path: '/$alumniId',
  getParentRoute: () => AlumniRoute,
} as any)
const AlumniCalendarRoute = AlumniCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AlumniRoute,
} as any)
const AlumniCommunicationsRoute = AlumniCommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => AlumniRoute,
} as any)
const AlumniDocumentsRoute = AlumniDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AlumniRoute,
} as any)
const AlumniInsightsRoute = AlumniInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AlumniRoute,
} as any)
const AlumniMatchingRoute = AlumniMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => AlumniRoute,
} as any)
const AlumniOperationsRoute = AlumniOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AlumniRoute,
} as any)
const AlumniPipelineRoute = AlumniPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AlumniRoute,
} as any)
const AlumniPortalRoute = AlumniPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AlumniRoute,
} as any)
const AlunosIndexRoute = AlunosIndexRouteImport.update({
  id: '/alunos/',
  path: '/alunos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosStudentIdRoute = AlunosStudentIdRouteImport.update({
  id: '/alunos/$studentId',
  path: '/alunos/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEmailChangeRoute = AuthEmailChangeRouteImport.update({
  id: '/auth/email-change',
  path: '/auth/email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicLinkRoute = AuthMagicLinkRouteImport.update({
  id: '/auth/magic-link',
  path: '/auth/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioIcsRoute = CalendarioIcsRouteImport.update({
  id: '/ics',
  path: '/ics',
  getParentRoute: () => CalendarioRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRhRoute = FinanceiroRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => FinanceiroRoute,
} as any)
const MatriculaSlugRoute = MatriculaSlugRouteImport.update({
  id: '/matricula/$slug',
  path: '/matricula/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PessoasIndexRoute = PessoasIndexRouteImport.update({
  id: '/pessoas/',
  path: '/pessoas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorPresencaRoute = ProfessorPresencaRouteImport.update({
  id: '/professor/presenca',
  path: '/professor/presenca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessoresTeacherIdRoute = ProfessoresTeacherIdRouteImport.update({
  id: '/professores/$teacherId',
  path: '/professores/$teacherId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosAcademicosRoute = RelatoriosAcademicosRouteImport.update({
  id: '/relatorios/academicos',
  path: '/relatorios/academicos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosFinanceirosRoute = RelatoriosFinanceirosRouteImport.update({
  id: '/relatorios/financeiros',
  path: '/relatorios/financeiros',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniAlumniIdPortfolioRoute = AlumniAlumniIdPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AlumniAlumniIdRoute,
} as any)
const AlumniPortalPortfolioRoute = AlumniPortalPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AlumniPortalRoute,
} as any)
const ApiCalendarIcsRoute = ApiCalendarIcsRouteImport.update({
  id: '/api/calendar/ics',
  path: '/api/calendar/ics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatracasDeviceScanRoute = ApiCatracasDeviceScanRouteImport.update({
  id: '/api/catracas/device-scan',
  path: '/api/catracas/device-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasAuditLogsRoute = ApiSaasAuditLogsRouteImport.update({
  id: '/api/saas/audit-logs',
  path: '/api/saas/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasDomainsRoute = ApiSaasDomainsRouteImport.update({
  id: '/api/saas/domains',
  path: '/api/saas/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasGatewayWebhooksRoute = ApiSaasGatewayWebhooksRouteImport.update({
  id: '/api/saas/gateway-webhooks',
  path: '/api/saas/gateway-webhooks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasMailboxesRoute = ApiSaasMailboxesRouteImport.update({
  id: '/api/saas/mailboxes',
  path: '/api/saas/mailboxes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasMeRoute = ApiSaasMeRouteImport.update({
  id: '/api/saas/me',
  path: '/api/saas/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasPlansRoute = ApiSaasPlansRouteImport.update({
  id: '/api/saas/plans',
  path: '/api/saas/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasPlatformAdminsRoute = ApiSaasPlatformAdminsRouteImport.update({
  id: '/api/saas/platform-admins',
  path: '/api/saas/platform-admins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasSignupRoute = ApiSaasSignupRouteImport.update({
  id: '/api/saas/signup',
  path: '/api/saas/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasStatsRoute = ApiSaasStatsRouteImport.update({
  id: '/api/saas/stats',
  path: '/api/saas/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasSubscriptionsRoute = ApiSaasSubscriptionsRouteImport.update({
  id: '/api/saas/subscriptions',
  path: '/api/saas/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasTenantsRoute = ApiSaasTenantsRouteImport.update({
  id: '/api/saas/tenants',
  path: '/api/saas/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTwilioSmsRoute = ApiWebhooksTwilioSmsRouteImport.update({
  id: '/api/webhooks/twilio-sms',
  path: '/api/webhooks/twilio-sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhatsappStatusRoute =
  ApiWebhooksWhatsappStatusRouteImport.update({
    id: '/api/webhooks/whatsapp-status',
    path: '/api/webhooks/whatsapp-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const FinanceiroRhFaltasRoute = FinanceiroRhFaltasRouteImport.update({
  id: '/faltas',
  path: '/faltas',
  getParentRoute: () => FinanceiroRhRoute,
} as any)
const FinanceiroRhFolhaRoute = FinanceiroRhFolhaRouteImport.update({
  id: '/folha',
  path: '/folha',
  getParentRoute: () => FinanceiroRhRoute,
} as any)
const FinanceiroRhPagamentosRoute = FinanceiroRhPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => FinanceiroRhRoute,
} as any)
const FinanceiroRhPresencaRoute = FinanceiroRhPresencaRouteImport.update({
  id: '/presenca',
  path: '/presenca',
  getParentRoute: () => FinanceiroRhRoute,
} as any)
const FinanceiroRhSalariosRoute = FinanceiroRhSalariosRouteImport.update({
  id: '/salarios',
  path: '/salarios',
  getParentRoute: () => FinanceiroRhRoute,
} as any)
const AlumniPortalPortfolioEducationRoute =
  AlumniPortalPortfolioEducationRouteImport.update({
    id: '/education',
    path: '/education',
    getParentRoute: () => AlumniPortalPortfolioRoute,
  } as any)
const AlumniPortalPortfolioPrintRoute =
  AlumniPortalPortfolioPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AlumniPortalPortfolioRoute,
  } as any)
const AlumniPortalPortfolioShowcaseRoute =
  AlumniPortalPortfolioShowcaseRouteImport.update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: () => AlumniPortalPortfolioRoute,
  } as any)
const ApiFinanceGatewayConfirmRoute =
  ApiFinanceGatewayConfirmRouteImport.update({
    id: '/api/finance/gateway/confirm',
    path: '/api/finance/gateway/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFinancePayflowSettlementRoute =
  ApiFinancePayflowSettlementRouteImport.update({
    id: '/api/finance/payflow/settlement',
    path: '/api/finance/payflow/settlement',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsResendWebhookRoute =
  ApiIntegrationsResendWebhookRouteImport.update({
    id: '/api/integrations/resend/webhook',
    path: '/api/integrations/resend/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsZoomCallbackRoute =
  ApiIntegrationsZoomCallbackRouteImport.update({
    id: '/api/integrations/zoom/callback',
    path: '/api/integrations/zoom/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSaasDomainsCheckRoute = ApiSaasDomainsCheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => ApiSaasDomainsRoute,
} as any)
const ApiSaasDomainsPollRoute = ApiSaasDomainsPollRouteImport.update({
  id: '/poll',
  path: '/poll',
  getParentRoute: () => ApiSaasDomainsRoute,
} as any)
const ApiSaasDomainsStatusRoute = ApiSaasDomainsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiSaasDomainsRoute,
} as any)
const ApiSaasDomainsVerifyRoute = ApiSaasDomainsVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ApiSaasDomainsRoute,
} as any)
const ApiSaasEmailRoutesRoute = ApiSaasEmailRoutesRouteImport.update({
  id: '/api/saas/email/routes',
  path: '/api/saas/email/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaasPlatformAdminsRevokeRoute =
  ApiSaasPlatformAdminsRevokeRouteImport.update({
    id: '/revoke',
    path: '/revoke',
    getParentRoute: () => ApiSaasPlatformAdminsRoute,
  } as any)
const ApiSaasSubscriptionsBackfillRoute =
  ApiSaasSubscriptionsBackfillRouteImport.update({
    id: '/backfill',
    path: '/backfill',
    getParentRoute: () => ApiSaasSubscriptionsRoute,
  } as any)
const ApiSaasTenantsLookupRoute = ApiSaasTenantsLookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => ApiSaasTenantsRoute,
} as any)
const ApiSaasTenantsStatusRoute = ApiSaasTenantsStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ApiSaasTenantsRoute,
} as any)
const ApiSaasTenantsSubscriptionRoute =
  ApiSaasTenantsSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => ApiSaasTenantsRoute,
  } as any)
const ApiSaasUsageSyncRoute = ApiSaasUsageSyncRouteImport.update({
  id: '/api/saas/usage/sync',
  path: '/api/saas/usage/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFinanceGatewayUnitelConfirmRoute =
  ApiFinanceGatewayUnitelConfirmRouteImport.update({
    id: '/api/finance/gateway/unitel/confirm',
    path: '/api/finance/gateway/unitel/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/alumni': typeof AlumniRouteWithChildren
  '/arquivos': typeof ArquivosRoute
  '/calendario': typeof CalendarioRouteWithChildren
  '/catracas': typeof CatracasRoute
  '/comunicacoes': typeof ComunicacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-escola': typeof CriarEscolaRoute
  '/documentos': typeof DocumentosRoute
  '/faturas': typeof FaturasRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/importar': typeof ImportarRoute
  '/pedagogica': typeof PedagogicaRoute
  '/perfil': typeof PerfilRoute
  '/planos-aula': typeof PlanosAulaRoute
  '/saas-admin': typeof SaasAdminRoute
  '/alumni/$alumniId': typeof AlumniAlumniIdRouteWithChildren
  '/alumni/calendar': typeof AlumniCalendarRoute
  '/alumni/communications': typeof AlumniCommunicationsRoute
  '/alumni/documents': typeof AlumniDocumentsRoute
  '/alumni/insights': typeof AlumniInsightsRoute
  '/alumni/matching': typeof AlumniMatchingRoute
  '/alumni/operations': typeof AlumniOperationsRoute
  '/alumni/pipeline': typeof AlumniPipelineRoute
  '/alumni/portal': typeof AlumniPortalRouteWithChildren
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/auth/email-change': typeof AuthEmailChangeRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/calendario/ics': typeof CalendarioIcsRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/financeiro/rh': typeof FinanceiroRhRouteWithChildren
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/professor/presenca': typeof ProfessorPresencaRoute
  '/professores/$teacherId': typeof ProfessoresTeacherIdRoute
  '/relatorios/academicos': typeof RelatoriosAcademicosRoute
  '/relatorios/financeiros': typeof RelatoriosFinanceirosRoute
  '/alunos/': typeof AlunosIndexRoute
  '/pessoas/': typeof PessoasIndexRoute
  '/alumni/$alumniId/portfolio': typeof AlumniAlumniIdPortfolioRoute
  '/alumni/portal/portfolio': typeof AlumniPortalPortfolioRouteWithChildren
  '/api/calendar/ics': typeof ApiCalendarIcsRoute
  '/api/catracas/device-scan': typeof ApiCatracasDeviceScanRoute
  '/api/saas/audit-logs': typeof ApiSaasAuditLogsRoute
  '/api/saas/domains': typeof ApiSaasDomainsRouteWithChildren
  '/api/saas/gateway-webhooks': typeof ApiSaasGatewayWebhooksRoute
  '/api/saas/mailboxes': typeof ApiSaasMailboxesRoute
  '/api/saas/me': typeof ApiSaasMeRoute
  '/api/saas/plans': typeof ApiSaasPlansRoute
  '/api/saas/platform-admins': typeof ApiSaasPlatformAdminsRouteWithChildren
  '/api/saas/signup': typeof ApiSaasSignupRoute
  '/api/saas/stats': typeof ApiSaasStatsRoute
  '/api/saas/subscriptions': typeof ApiSaasSubscriptionsRouteWithChildren
  '/api/saas/tenants': typeof ApiSaasTenantsRouteWithChildren
  '/api/webhooks/twilio-sms': typeof ApiWebhooksTwilioSmsRoute
  '/api/webhooks/whatsapp-status': typeof ApiWebhooksWhatsappStatusRoute
  '/financeiro/rh/faltas': typeof FinanceiroRhFaltasRoute
  '/financeiro/rh/folha': typeof FinanceiroRhFolhaRoute
  '/financeiro/rh/pagamentos': typeof FinanceiroRhPagamentosRoute
  '/financeiro/rh/presenca': typeof FinanceiroRhPresencaRoute
  '/financeiro/rh/salarios': typeof FinanceiroRhSalariosRoute
  '/alumni/portal/portfolio/education': typeof AlumniPortalPortfolioEducationRoute
  '/alumni/portal/portfolio/print': typeof AlumniPortalPortfolioPrintRoute
  '/alumni/portal/portfolio/showcase': typeof AlumniPortalPortfolioShowcaseRoute
  '/api/finance/gateway/confirm': typeof ApiFinanceGatewayConfirmRoute
  '/api/finance/payflow/settlement': typeof ApiFinancePayflowSettlementRoute
  '/api/integrations/resend/webhook': typeof ApiIntegrationsResendWebhookRoute
  '/api/integrations/zoom/callback': typeof ApiIntegrationsZoomCallbackRoute
  '/api/saas/domains/check': typeof ApiSaasDomainsCheckRoute
  '/api/saas/domains/poll': typeof ApiSaasDomainsPollRoute
  '/api/saas/domains/status': typeof ApiSaasDomainsStatusRoute
  '/api/saas/domains/verify': typeof ApiSaasDomainsVerifyRoute
  '/api/saas/email/routes': typeof ApiSaasEmailRoutesRoute
  '/api/saas/platform-admins/revoke': typeof ApiSaasPlatformAdminsRevokeRoute
  '/api/saas/subscriptions/backfill': typeof ApiSaasSubscriptionsBackfillRoute
  '/api/saas/tenants/lookup': typeof ApiSaasTenantsLookupRoute
  '/api/saas/tenants/status': typeof ApiSaasTenantsStatusRoute
  '/api/saas/tenants/subscription': typeof ApiSaasTenantsSubscriptionRoute
  '/api/saas/usage/sync': typeof ApiSaasUsageSyncRoute
  '/api/finance/gateway/unitel/confirm': typeof ApiFinanceGatewayUnitelConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/alumni': typeof AlumniRouteWithChildren
  '/arquivos': typeof ArquivosRoute
  '/calendario': typeof CalendarioRouteWithChildren
  '/catracas': typeof CatracasRoute
  '/comunicacoes': typeof ComunicacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-escola': typeof CriarEscolaRoute
  '/documentos': typeof DocumentosRoute
  '/faturas': typeof FaturasRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/importar': typeof ImportarRoute
  '/pedagogica': typeof PedagogicaRoute
  '/perfil': typeof PerfilRoute
  '/planos-aula': typeof PlanosAulaRoute
  '/saas-admin': typeof SaasAdminRoute
  '/alumni/$alumniId': typeof AlumniAlumniIdRouteWithChildren
  '/alumni/calendar': typeof AlumniCalendarRoute
  '/alumni/communications': typeof AlumniCommunicationsRoute
  '/alumni/documents': typeof AlumniDocumentsRoute
  '/alumni/insights': typeof AlumniInsightsRoute
  '/alumni/matching': typeof AlumniMatchingRoute
  '/alumni/operations': typeof AlumniOperationsRoute
  '/alumni/pipeline': typeof AlumniPipelineRoute
  '/alumni/portal': typeof AlumniPortalRouteWithChildren
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/auth/email-change': typeof AuthEmailChangeRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/calendario/ics': typeof CalendarioIcsRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/financeiro/rh': typeof FinanceiroRhRouteWithChildren
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/professor/presenca': typeof ProfessorPresencaRoute
  '/professores/$teacherId': typeof ProfessoresTeacherIdRoute
  '/relatorios/academicos': typeof RelatoriosAcademicosRoute
  '/relatorios/financeiros': typeof RelatoriosFinanceirosRoute
  '/alunos': typeof AlunosIndexRoute
  '/pessoas': typeof PessoasIndexRoute
  '/alumni/$alumniId/portfolio': typeof AlumniAlumniIdPortfolioRoute
  '/alumni/portal/portfolio': typeof AlumniPortalPortfolioRouteWithChildren
  '/api/calendar/ics': typeof ApiCalendarIcsRoute
  '/api/catracas/device-scan': typeof ApiCatracasDeviceScanRoute
  '/api/saas/audit-logs': typeof ApiSaasAuditLogsRoute
  '/api/saas/domains': typeof ApiSaasDomainsRouteWithChildren
  '/api/saas/gateway-webhooks': typeof ApiSaasGatewayWebhooksRoute
  '/api/saas/mailboxes': typeof ApiSaasMailboxesRoute
  '/api/saas/me': typeof ApiSaasMeRoute
  '/api/saas/plans': typeof ApiSaasPlansRoute
  '/api/saas/platform-admins': typeof ApiSaasPlatformAdminsRouteWithChildren
  '/api/saas/signup': typeof ApiSaasSignupRoute
  '/api/saas/stats': typeof ApiSaasStatsRoute
  '/api/saas/subscriptions': typeof ApiSaasSubscriptionsRouteWithChildren
  '/api/saas/tenants': typeof ApiSaasTenantsRouteWithChildren
  '/api/webhooks/twilio-sms': typeof ApiWebhooksTwilioSmsRoute
  '/api/webhooks/whatsapp-status': typeof ApiWebhooksWhatsappStatusRoute
  '/financeiro/rh/faltas': typeof FinanceiroRhFaltasRoute
  '/financeiro/rh/folha': typeof FinanceiroRhFolhaRoute
  '/financeiro/rh/pagamentos': typeof FinanceiroRhPagamentosRoute
  '/financeiro/rh/presenca': typeof FinanceiroRhPresencaRoute
  '/financeiro/rh/salarios': typeof FinanceiroRhSalariosRoute
  '/alumni/portal/portfolio/education': typeof AlumniPortalPortfolioEducationRoute
  '/alumni/portal/portfolio/print': typeof AlumniPortalPortfolioPrintRoute
  '/alumni/portal/portfolio/showcase': typeof AlumniPortalPortfolioShowcaseRoute
  '/api/finance/gateway/confirm': typeof ApiFinanceGatewayConfirmRoute
  '/api/finance/payflow/settlement': typeof ApiFinancePayflowSettlementRoute
  '/api/integrations/resend/webhook': typeof ApiIntegrationsResendWebhookRoute
  '/api/integrations/zoom/callback': typeof ApiIntegrationsZoomCallbackRoute
  '/api/saas/domains/check': typeof ApiSaasDomainsCheckRoute
  '/api/saas/domains/poll': typeof ApiSaasDomainsPollRoute
  '/api/saas/domains/status': typeof ApiSaasDomainsStatusRoute
  '/api/saas/domains/verify': typeof ApiSaasDomainsVerifyRoute
  '/api/saas/email/routes': typeof ApiSaasEmailRoutesRoute
  '/api/saas/platform-admins/revoke': typeof ApiSaasPlatformAdminsRevokeRoute
  '/api/saas/subscriptions/backfill': typeof ApiSaasSubscriptionsBackfillRoute
  '/api/saas/tenants/lookup': typeof ApiSaasTenantsLookupRoute
  '/api/saas/tenants/status': typeof ApiSaasTenantsStatusRoute
  '/api/saas/tenants/subscription': typeof ApiSaasTenantsSubscriptionRoute
  '/api/saas/usage/sync': typeof ApiSaasUsageSyncRoute
  '/api/finance/gateway/unitel/confirm': typeof ApiFinanceGatewayUnitelConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acessos': typeof AcessosRoute
  '/alterar-senha': typeof AlterarSenhaRoute
  '/alumni': typeof AlumniRouteWithChildren
  '/arquivos': typeof ArquivosRoute
  '/calendario': typeof CalendarioRouteWithChildren
  '/catracas': typeof CatracasRoute
  '/comunicacoes': typeof ComunicacoesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/criar-escola': typeof CriarEscolaRoute
  '/documentos': typeof DocumentosRoute
  '/faturas': typeof FaturasRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/importar': typeof ImportarRoute
  '/pedagogica': typeof PedagogicaRoute
  '/perfil': typeof PerfilRoute
  '/planos-aula': typeof PlanosAulaRoute
  '/saas-admin': typeof SaasAdminRoute
  '/alumni/$alumniId': typeof AlumniAlumniIdRouteWithChildren
  '/alumni/calendar': typeof AlumniCalendarRoute
  '/alumni/communications': typeof AlumniCommunicationsRoute
  '/alumni/documents': typeof AlumniDocumentsRoute
  '/alumni/insights': typeof AlumniInsightsRoute
  '/alumni/matching': typeof AlumniMatchingRoute
  '/alumni/operations': typeof AlumniOperationsRoute
  '/alumni/pipeline': typeof AlumniPipelineRoute
  '/alumni/portal': typeof AlumniPortalRouteWithChildren
  '/alunos/$studentId': typeof AlunosStudentIdRoute
  '/auth/email-change': typeof AuthEmailChangeRoute
  '/auth/magic-link': typeof AuthMagicLinkRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/calendario/ics': typeof CalendarioIcsRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/financeiro/rh': typeof FinanceiroRhRouteWithChildren
  '/matricula/$slug': typeof MatriculaSlugRoute
  '/professor/presenca': typeof ProfessorPresencaRoute
  '/professores/$teacherId': typeof ProfessoresTeacherIdRoute
  '/relatorios/academicos': typeof RelatoriosAcademicosRoute
  '/relatorios/financeiros': typeof RelatoriosFinanceirosRoute
  '/alunos/': typeof AlunosIndexRoute
  '/pessoas/': typeof PessoasIndexRoute
  '/alumni/$alumniId/portfolio': typeof AlumniAlumniIdPortfolioRoute
  '/alumni/portal/portfolio': typeof AlumniPortalPortfolioRouteWithChildren
  '/api/calendar/ics': typeof ApiCalendarIcsRoute
  '/api/catracas/device-scan': typeof ApiCatracasDeviceScanRoute
  '/api/saas/audit-logs': typeof ApiSaasAuditLogsRoute
  '/api/saas/domains': typeof ApiSaasDomainsRouteWithChildren
  '/api/saas/gateway-webhooks': typeof ApiSaasGatewayWebhooksRoute
  '/api/saas/mailboxes': typeof ApiSaasMailboxesRoute
  '/api/saas/me': typeof ApiSaasMeRoute
  '/api/saas/plans': typeof ApiSaasPlansRoute
  '/api/saas/platform-admins': typeof ApiSaasPlatformAdminsRouteWithChildren
  '/api/saas/signup': typeof ApiSaasSignupRoute
  '/api/saas/stats': typeof ApiSaasStatsRoute
  '/api/saas/subscriptions': typeof ApiSaasSubscriptionsRouteWithChildren
  '/api/saas/tenants': typeof ApiSaasTenantsRouteWithChildren
  '/api/webhooks/twilio-sms': typeof ApiWebhooksTwilioSmsRoute
  '/api/webhooks/whatsapp-status': typeof ApiWebhooksWhatsappStatusRoute
  '/financeiro/rh/faltas': typeof FinanceiroRhFaltasRoute
  '/financeiro/rh/folha': typeof FinanceiroRhFolhaRoute
  '/financeiro/rh/pagamentos': typeof FinanceiroRhPagamentosRoute
  '/financeiro/rh/presenca': typeof FinanceiroRhPresencaRoute
  '/financeiro/rh/salarios': typeof FinanceiroRhSalariosRoute
  '/alumni/portal/portfolio/education': typeof AlumniPortalPortfolioEducationRoute
  '/alumni/portal/portfolio/print': typeof AlumniPortalPortfolioPrintRoute
  '/alumni/portal/portfolio/showcase': typeof AlumniPortalPortfolioShowcaseRoute
  '/api/finance/gateway/confirm': typeof ApiFinanceGatewayConfirmRoute
  '/api/finance/payflow/settlement': typeof ApiFinancePayflowSettlementRoute
  '/api/integrations/resend/webhook': typeof ApiIntegrationsResendWebhookRoute
  '/api/integrations/zoom/callback': typeof ApiIntegrationsZoomCallbackRoute
  '/api/saas/domains/check': typeof ApiSaasDomainsCheckRoute
  '/api/saas/domains/poll': typeof ApiSaasDomainsPollRoute
  '/api/saas/domains/status': typeof ApiSaasDomainsStatusRoute
  '/api/saas/domains/verify': typeof ApiSaasDomainsVerifyRoute
  '/api/saas/email/routes': typeof ApiSaasEmailRoutesRoute
  '/api/saas/platform-admins/revoke': typeof ApiSaasPlatformAdminsRevokeRoute
  '/api/saas/subscriptions/backfill': typeof ApiSaasSubscriptionsBackfillRoute
  '/api/saas/tenants/lookup': typeof ApiSaasTenantsLookupRoute
  '/api/saas/tenants/status': typeof ApiSaasTenantsStatusRoute
  '/api/saas/tenants/subscription': typeof ApiSaasTenantsSubscriptionRoute
  '/api/saas/usage/sync': typeof ApiSaasUsageSyncRoute
  '/api/finance/gateway/unitel/confirm': typeof ApiFinanceGatewayUnitelConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acessos'
    | '/alterar-senha'
    | '/alumni'
    | '/arquivos'
    | '/calendario'
    | '/catracas'
    | '/comunicacoes'
    | '/configuracoes'
    | '/criar-escola'
    | '/documentos'
    | '/faturas'
    | '/financeiro'
    | '/importar'
    | '/pedagogica'
    | '/perfil'
    | '/planos-aula'
    | '/saas-admin'
    | '/alumni/$alumniId'
    | '/alumni/calendar'
    | '/alumni/communications'
    | '/alumni/documents'
    | '/alumni/insights'
    | '/alumni/matching'
    | '/alumni/operations'
    | '/alumni/pipeline'
    | '/alumni/portal'
    | '/alunos/$studentId'
    | '/auth/email-change'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/calendario/ics'
    | '/convite/$token'
    | '/financeiro/rh'
    | '/matricula/$slug'
    | '/professor/presenca'
    | '/professores/$teacherId'
    | '/relatorios/academicos'
    | '/relatorios/financeiros'
    | '/alunos/'
    | '/pessoas/'
    | '/alumni/$alumniId/portfolio'
    | '/alumni/portal/portfolio'
    | '/api/calendar/ics'
    | '/api/catracas/device-scan'
    | '/api/saas/audit-logs'
    | '/api/saas/domains'
    | '/api/saas/gateway-webhooks'
    | '/api/saas/mailboxes'
    | '/api/saas/me'
    | '/api/saas/plans'
    | '/api/saas/platform-admins'
    | '/api/saas/signup'
    | '/api/saas/stats'
    | '/api/saas/subscriptions'
    | '/api/saas/tenants'
    | '/api/webhooks/twilio-sms'
    | '/api/webhooks/whatsapp-status'
    | '/financeiro/rh/faltas'
    | '/financeiro/rh/folha'
    | '/financeiro/rh/pagamentos'
    | '/financeiro/rh/presenca'
    | '/financeiro/rh/salarios'
    | '/alumni/portal/portfolio/education'
    | '/alumni/portal/portfolio/print'
    | '/alumni/portal/portfolio/showcase'
    | '/api/finance/gateway/confirm'
    | '/api/finance/payflow/settlement'
    | '/api/integrations/resend/webhook'
    | '/api/integrations/zoom/callback'
    | '/api/saas/domains/check'
    | '/api/saas/domains/poll'
    | '/api/saas/domains/status'
    | '/api/saas/domains/verify'
    | '/api/saas/email/routes'
    | '/api/saas/platform-admins/revoke'
    | '/api/saas/subscriptions/backfill'
    | '/api/saas/tenants/lookup'
    | '/api/saas/tenants/status'
    | '/api/saas/tenants/subscription'
    | '/api/saas/usage/sync'
    | '/api/finance/gateway/unitel/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acessos'
    | '/alterar-senha'
    | '/alumni'
    | '/arquivos'
    | '/calendario'
    | '/catracas'
    | '/comunicacoes'
    | '/configuracoes'
    | '/criar-escola'
    | '/documentos'
    | '/faturas'
    | '/financeiro'
    | '/importar'
    | '/pedagogica'
    | '/perfil'
    | '/planos-aula'
    | '/saas-admin'
    | '/alumni/$alumniId'
    | '/alumni/calendar'
    | '/alumni/communications'
    | '/alumni/documents'
    | '/alumni/insights'
    | '/alumni/matching'
    | '/alumni/operations'
    | '/alumni/pipeline'
    | '/alumni/portal'
    | '/alunos/$studentId'
    | '/auth/email-change'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/calendario/ics'
    | '/convite/$token'
    | '/financeiro/rh'
    | '/matricula/$slug'
    | '/professor/presenca'
    | '/professores/$teacherId'
    | '/relatorios/academicos'
    | '/relatorios/financeiros'
    | '/alunos'
    | '/pessoas'
    | '/alumni/$alumniId/portfolio'
    | '/alumni/portal/portfolio'
    | '/api/calendar/ics'
    | '/api/catracas/device-scan'
    | '/api/saas/audit-logs'
    | '/api/saas/domains'
    | '/api/saas/gateway-webhooks'
    | '/api/saas/mailboxes'
    | '/api/saas/me'
    | '/api/saas/plans'
    | '/api/saas/platform-admins'
    | '/api/saas/signup'
    | '/api/saas/stats'
    | '/api/saas/subscriptions'
    | '/api/saas/tenants'
    | '/api/webhooks/twilio-sms'
    | '/api/webhooks/whatsapp-status'
    | '/financeiro/rh/faltas'
    | '/financeiro/rh/folha'
    | '/financeiro/rh/pagamentos'
    | '/financeiro/rh/presenca'
    | '/financeiro/rh/salarios'
    | '/alumni/portal/portfolio/education'
    | '/alumni/portal/portfolio/print'
    | '/alumni/portal/portfolio/showcase'
    | '/api/finance/gateway/confirm'
    | '/api/finance/payflow/settlement'
    | '/api/integrations/resend/webhook'
    | '/api/integrations/zoom/callback'
    | '/api/saas/domains/check'
    | '/api/saas/domains/poll'
    | '/api/saas/domains/status'
    | '/api/saas/domains/verify'
    | '/api/saas/email/routes'
    | '/api/saas/platform-admins/revoke'
    | '/api/saas/subscriptions/backfill'
    | '/api/saas/tenants/lookup'
    | '/api/saas/tenants/status'
    | '/api/saas/tenants/subscription'
    | '/api/saas/usage/sync'
    | '/api/finance/gateway/unitel/confirm'
  id:
    | '__root__'
    | '/'
    | '/acessos'
    | '/alterar-senha'
    | '/alumni'
    | '/arquivos'
    | '/calendario'
    | '/catracas'
    | '/comunicacoes'
    | '/configuracoes'
    | '/criar-escola'
    | '/documentos'
    | '/faturas'
    | '/financeiro'
    | '/importar'
    | '/pedagogica'
    | '/perfil'
    | '/planos-aula'
    | '/saas-admin'
    | '/alumni/$alumniId'
    | '/alumni/calendar'
    | '/alumni/communications'
    | '/alumni/documents'
    | '/alumni/insights'
    | '/alumni/matching'
    | '/alumni/operations'
    | '/alumni/pipeline'
    | '/alumni/portal'
    | '/alunos/$studentId'
    | '/auth/email-change'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/calendario/ics'
    | '/convite/$token'
    | '/financeiro/rh'
    | '/matricula/$slug'
    | '/professor/presenca'
    | '/professores/$teacherId'
    | '/relatorios/academicos'
    | '/relatorios/financeiros'
    | '/alunos/'
    | '/pessoas/'
    | '/alumni/$alumniId/portfolio'
    | '/alumni/portal/portfolio'
    | '/api/calendar/ics'
    | '/api/catracas/device-scan'
    | '/api/saas/audit-logs'
    | '/api/saas/domains'
    | '/api/saas/gateway-webhooks'
    | '/api/saas/mailboxes'
    | '/api/saas/me'
    | '/api/saas/plans'
    | '/api/saas/platform-admins'
    | '/api/saas/signup'
    | '/api/saas/stats'
    | '/api/saas/subscriptions'
    | '/api/saas/tenants'
    | '/api/webhooks/twilio-sms'
    | '/api/webhooks/whatsapp-status'
    | '/financeiro/rh/faltas'
    | '/financeiro/rh/folha'
    | '/financeiro/rh/pagamentos'
    | '/financeiro/rh/presenca'
    | '/financeiro/rh/salarios'
    | '/alumni/portal/portfolio/education'
    | '/alumni/portal/portfolio/print'
    | '/alumni/portal/portfolio/showcase'
    | '/api/finance/gateway/confirm'
    | '/api/finance/payflow/settlement'
    | '/api/integrations/resend/webhook'
    | '/api/integrations/zoom/callback'
    | '/api/saas/domains/check'
    | '/api/saas/domains/poll'
    | '/api/saas/domains/status'
    | '/api/saas/domains/verify'
    | '/api/saas/email/routes'
    | '/api/saas/platform-admins/revoke'
    | '/api/saas/subscriptions/backfill'
    | '/api/saas/tenants/lookup'
    | '/api/saas/tenants/status'
    | '/api/saas/tenants/subscription'
    | '/api/saas/usage/sync'
    | '/api/finance/gateway/unitel/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessosRoute: typeof AcessosRoute
  AlterarSenhaRoute: typeof AlterarSenhaRoute
  AlumniRoute: typeof AlumniRouteWithChildren
  ArquivosRoute: typeof ArquivosRoute
  CalendarioRoute: typeof CalendarioRouteWithChildren
  CatracasRoute: typeof CatracasRoute
  ComunicacoesRoute: typeof ComunicacoesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CriarEscolaRoute: typeof CriarEscolaRoute
  DocumentosRoute: typeof DocumentosRoute
  FaturasRoute: typeof FaturasRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  ImportarRoute: typeof ImportarRoute
  PedagogicaRoute: typeof PedagogicaRoute
  PerfilRoute: typeof PerfilRoute
  PlanosAulaRoute: typeof PlanosAulaRoute
  SaasAdminRoute: typeof SaasAdminRoute
  AlunosStudentIdRoute: typeof AlunosStudentIdRoute
  AuthEmailChangeRoute: typeof AuthEmailChangeRoute
  AuthMagicLinkRoute: typeof AuthMagicLinkRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  MatriculaSlugRoute: typeof MatriculaSlugRoute
  ProfessorPresencaRoute: typeof ProfessorPresencaRoute
  ProfessoresTeacherIdRoute: typeof ProfessoresTeacherIdRoute
  RelatoriosAcademicosRoute: typeof RelatoriosAcademicosRoute
  RelatoriosFinanceirosRoute: typeof RelatoriosFinanceirosRoute
  AlunosIndexRoute: typeof AlunosIndexRoute
  PessoasIndexRoute: typeof PessoasIndexRoute
  ApiCalendarIcsRoute: typeof ApiCalendarIcsRoute
  ApiCatracasDeviceScanRoute: typeof ApiCatracasDeviceScanRoute
  ApiSaasAuditLogsRoute: typeof ApiSaasAuditLogsRoute
  ApiSaasDomainsRoute: typeof ApiSaasDomainsRouteWithChildren
  ApiSaasGatewayWebhooksRoute: typeof ApiSaasGatewayWebhooksRoute
  ApiSaasMailboxesRoute: typeof ApiSaasMailboxesRoute
  ApiSaasMeRoute: typeof ApiSaasMeRoute
  ApiSaasPlansRoute: typeof ApiSaasPlansRoute
  ApiSaasPlatformAdminsRoute: typeof ApiSaasPlatformAdminsRouteWithChildren
  ApiSaasSignupRoute: typeof ApiSaasSignupRoute
  ApiSaasStatsRoute: typeof ApiSaasStatsRoute
  ApiSaasSubscriptionsRoute: typeof ApiSaasSubscriptionsRouteWithChildren
  ApiSaasTenantsRoute: typeof ApiSaasTenantsRouteWithChildren
  ApiWebhooksTwilioSmsRoute: typeof ApiWebhooksTwilioSmsRoute
  ApiWebhooksWhatsappStatusRoute: typeof ApiWebhooksWhatsappStatusRoute
  ApiFinanceGatewayConfirmRoute: typeof ApiFinanceGatewayConfirmRoute
  ApiFinancePayflowSettlementRoute: typeof ApiFinancePayflowSettlementRoute
  ApiIntegrationsResendWebhookRoute: typeof ApiIntegrationsResendWebhookRoute
  ApiIntegrationsZoomCallbackRoute: typeof ApiIntegrationsZoomCallbackRoute
  ApiSaasEmailRoutesRoute: typeof ApiSaasEmailRoutesRoute
  ApiSaasUsageSyncRoute: typeof ApiSaasUsageSyncRoute
  ApiFinanceGatewayUnitelConfirmRoute: typeof ApiFinanceGatewayUnitelConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acessos': {
      id: '/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AcessosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha': {
      id: '/alterar-senha'
      path: '/alterar-senha'
      fullPath: '/alterar-senha'
      preLoaderRoute: typeof AlterarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivos': {
      id: '/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof ArquivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catracas': {
      id: '/catracas'
      path: '/catracas'
      fullPath: '/catracas'
      preLoaderRoute: typeof CatracasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacoes': {
      id: '/comunicacoes'
      path: '/comunicacoes'
      fullPath: '/comunicacoes'
      preLoaderRoute: typeof ComunicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-escola': {
      id: '/criar-escola'
      path: '/criar-escola'
      fullPath: '/criar-escola'
      preLoaderRoute: typeof CriarEscolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faturas': {
      id: '/faturas'
      path: '/faturas'
      fullPath: '/faturas'
      preLoaderRoute: typeof FaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedagogica': {
      id: '/pedagogica'
      path: '/pedagogica'
      fullPath: '/pedagogica'
      preLoaderRoute: typeof PedagogicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos-aula': {
      id: '/planos-aula'
      path: '/planos-aula'
      fullPath: '/planos-aula'
      preLoaderRoute: typeof PlanosAulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas-admin': {
      id: '/saas-admin'
      path: '/saas-admin'
      fullPath: '/saas-admin'
      preLoaderRoute: typeof SaasAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni/$alumniId': {
      id: '/alumni/$alumniId'
      path: '/$alumniId'
      fullPath: '/alumni/$alumniId'
      preLoaderRoute: typeof AlumniAlumniIdRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alumni/calendar': {
      id: '/alumni/calendar'
      path: '/calendar'
      fullPath: '/alumni/calendar'
      preLoaderRoute: typeof AlumniCalendarRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alumni/communications': {
      id: '/alumni/communications'
      path: '/communications'
      fullPath: '/alumni/communications'
      preLoaderRoute: typeof AlumniCommunicationsRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alumni/documents': {
      id: '/alumni/documents'
      path: '/documents'
      fullPath: '/alumni/documents'
      preLoaderRoute: typeof AlumniDocumentsRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alumni/insights': {
      id: '/alumni/insights'
      path: '/insights'
      fullPath: '/alumni/insights'
      preLoaderRoute: typeof AlumniInsightsRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alumni/matching': {
      id: '/alumni/matching'
      path: '/matching'
      fullPath: '/alumni/matching'
      preLoaderRoute: typeof AlumniMatchingRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alumni/operations': {
      id: '/alumni/operations'
      path: '/operations'
      fullPath: '/alumni/operations'
      preLoaderRoute: typeof AlumniOperationsRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alumni/pipeline': {
      id: '/alumni/pipeline'
      path: '/pipeline'
      fullPath: '/alumni/pipeline'
      preLoaderRoute: typeof AlumniPipelineRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alumni/portal': {
      id: '/alumni/portal'
      path: '/portal'
      fullPath: '/alumni/portal'
      preLoaderRoute: typeof AlumniPortalRouteImport
      parentRoute: typeof AlumniRoute
    }
    '/alunos/': {
      id: '/alunos/'
      path: '/alunos'
      fullPath: '/alunos/'
      preLoaderRoute: typeof AlunosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/$studentId': {
      id: '/alunos/$studentId'
      path: '/alunos/$studentId'
      fullPath: '/alunos/$studentId'
      preLoaderRoute: typeof AlunosStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/email-change': {
      id: '/auth/email-change'
      path: '/auth/email-change'
      fullPath: '/auth/email-change'
      preLoaderRoute: typeof AuthEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic-link': {
      id: '/auth/magic-link'
      path: '/auth/magic-link'
      fullPath: '/auth/magic-link'
      preLoaderRoute: typeof AuthMagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario/ics': {
      id: '/calendario/ics'
      path: '/ics'
      fullPath: '/calendario/ics'
      preLoaderRoute: typeof CalendarioIcsRouteImport
      parentRoute: typeof CalendarioRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/rh': {
      id: '/financeiro/rh'
      path: '/rh'
      fullPath: '/financeiro/rh'
      preLoaderRoute: typeof FinanceiroRhRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/matricula/$slug': {
      id: '/matricula/$slug'
      path: '/matricula/$slug'
      fullPath: '/matricula/$slug'
      preLoaderRoute: typeof MatriculaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pessoas/': {
      id: '/pessoas/'
      path: '/pessoas'
      fullPath: '/pessoas/'
      preLoaderRoute: typeof PessoasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor/presenca': {
      id: '/professor/presenca'
      path: '/professor/presenca'
      fullPath: '/professor/presenca'
      preLoaderRoute: typeof ProfessorPresencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores/$teacherId': {
      id: '/professores/$teacherId'
      path: '/professores/$teacherId'
      fullPath: '/professores/$teacherId'
      preLoaderRoute: typeof ProfessoresTeacherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/academicos': {
      id: '/relatorios/academicos'
      path: '/relatorios/academicos'
      fullPath: '/relatorios/academicos'
      preLoaderRoute: typeof RelatoriosAcademicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios/financeiros': {
      id: '/relatorios/financeiros'
      path: '/relatorios/financeiros'
      fullPath: '/relatorios/financeiros'
      preLoaderRoute: typeof RelatoriosFinanceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni/$alumniId/portfolio': {
      id: '/alumni/$alumniId/portfolio'
      path: '/portfolio'
      fullPath: '/alumni/$alumniId/portfolio'
      preLoaderRoute: typeof AlumniAlumniIdPortfolioRouteImport
      parentRoute: typeof AlumniAlumniIdRoute
    }
    '/alumni/portal/portfolio': {
      id: '/alumni/portal/portfolio'
      path: '/portfolio'
      fullPath: '/alumni/portal/portfolio'
      preLoaderRoute: typeof AlumniPortalPortfolioRouteImport
      parentRoute: typeof AlumniPortalRoute
    }
    '/api/calendar/ics': {
      id: '/api/calendar/ics'
      path: '/api/calendar/ics'
      fullPath: '/api/calendar/ics'
      preLoaderRoute: typeof ApiCalendarIcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catracas/device-scan': {
      id: '/api/catracas/device-scan'
      path: '/api/catracas/device-scan'
      fullPath: '/api/catracas/device-scan'
      preLoaderRoute: typeof ApiCatracasDeviceScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/audit-logs': {
      id: '/api/saas/audit-logs'
      path: '/api/saas/audit-logs'
      fullPath: '/api/saas/audit-logs'
      preLoaderRoute: typeof ApiSaasAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/domains': {
      id: '/api/saas/domains'
      path: '/api/saas/domains'
      fullPath: '/api/saas/domains'
      preLoaderRoute: typeof ApiSaasDomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/gateway-webhooks': {
      id: '/api/saas/gateway-webhooks'
      path: '/api/saas/gateway-webhooks'
      fullPath: '/api/saas/gateway-webhooks'
      preLoaderRoute: typeof ApiSaasGatewayWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/mailboxes': {
      id: '/api/saas/mailboxes'
      path: '/api/saas/mailboxes'
      fullPath: '/api/saas/mailboxes'
      preLoaderRoute: typeof ApiSaasMailboxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/me': {
      id: '/api/saas/me'
      path: '/api/saas/me'
      fullPath: '/api/saas/me'
      preLoaderRoute: typeof ApiSaasMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/plans': {
      id: '/api/saas/plans'
      path: '/api/saas/plans'
      fullPath: '/api/saas/plans'
      preLoaderRoute: typeof ApiSaasPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/platform-admins': {
      id: '/api/saas/platform-admins'
      path: '/api/saas/platform-admins'
      fullPath: '/api/saas/platform-admins'
      preLoaderRoute: typeof ApiSaasPlatformAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/signup': {
      id: '/api/saas/signup'
      path: '/api/saas/signup'
      fullPath: '/api/saas/signup'
      preLoaderRoute: typeof ApiSaasSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/stats': {
      id: '/api/saas/stats'
      path: '/api/saas/stats'
      fullPath: '/api/saas/stats'
      preLoaderRoute: typeof ApiSaasStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/subscriptions': {
      id: '/api/saas/subscriptions'
      path: '/api/saas/subscriptions'
      fullPath: '/api/saas/subscriptions'
      preLoaderRoute: typeof ApiSaasSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/tenants': {
      id: '/api/saas/tenants'
      path: '/api/saas/tenants'
      fullPath: '/api/saas/tenants'
      preLoaderRoute: typeof ApiSaasTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/twilio-sms': {
      id: '/api/webhooks/twilio-sms'
      path: '/api/webhooks/twilio-sms'
      fullPath: '/api/webhooks/twilio-sms'
      preLoaderRoute: typeof ApiWebhooksTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whatsapp-status': {
      id: '/api/webhooks/whatsapp-status'
      path: '/api/webhooks/whatsapp-status'
      fullPath: '/api/webhooks/whatsapp-status'
      preLoaderRoute: typeof ApiWebhooksWhatsappStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro/rh/faltas': {
      id: '/financeiro/rh/faltas'
      path: '/faltas'
      fullPath: '/financeiro/rh/faltas'
      preLoaderRoute: typeof FinanceiroRhFaltasRouteImport
      parentRoute: typeof FinanceiroRhRoute
    }
    '/financeiro/rh/folha': {
      id: '/financeiro/rh/folha'
      path: '/folha'
      fullPath: '/financeiro/rh/folha'
      preLoaderRoute: typeof FinanceiroRhFolhaRouteImport
      parentRoute: typeof FinanceiroRhRoute
    }
    '/financeiro/rh/pagamentos': {
      id: '/financeiro/rh/pagamentos'
      path: '/pagamentos'
      fullPath: '/financeiro/rh/pagamentos'
      preLoaderRoute: typeof FinanceiroRhPagamentosRouteImport
      parentRoute: typeof FinanceiroRhRoute
    }
    '/financeiro/rh/presenca': {
      id: '/financeiro/rh/presenca'
      path: '/presenca'
      fullPath: '/financeiro/rh/presenca'
      preLoaderRoute: typeof FinanceiroRhPresencaRouteImport
      parentRoute: typeof FinanceiroRhRoute
    }
    '/financeiro/rh/salarios': {
      id: '/financeiro/rh/salarios'
      path: '/salarios'
      fullPath: '/financeiro/rh/salarios'
      preLoaderRoute: typeof FinanceiroRhSalariosRouteImport
      parentRoute: typeof FinanceiroRhRoute
    }
    '/alumni/portal/portfolio/education': {
      id: '/alumni/portal/portfolio/education'
      path: '/education'
      fullPath: '/alumni/portal/portfolio/education'
      preLoaderRoute: typeof AlumniPortalPortfolioEducationRouteImport
      parentRoute: typeof AlumniPortalPortfolioRoute
    }
    '/alumni/portal/portfolio/print': {
      id: '/alumni/portal/portfolio/print'
      path: '/print'
      fullPath: '/alumni/portal/portfolio/print'
      preLoaderRoute: typeof AlumniPortalPortfolioPrintRouteImport
      parentRoute: typeof AlumniPortalPortfolioRoute
    }
    '/alumni/portal/portfolio/showcase': {
      id: '/alumni/portal/portfolio/showcase'
      path: '/showcase'
      fullPath: '/alumni/portal/portfolio/showcase'
      preLoaderRoute: typeof AlumniPortalPortfolioShowcaseRouteImport
      parentRoute: typeof AlumniPortalPortfolioRoute
    }
    '/api/finance/gateway/confirm': {
      id: '/api/finance/gateway/confirm'
      path: '/api/finance/gateway/confirm'
      fullPath: '/api/finance/gateway/confirm'
      preLoaderRoute: typeof ApiFinanceGatewayConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/payflow/settlement': {
      id: '/api/finance/payflow/settlement'
      path: '/api/finance/payflow/settlement'
      fullPath: '/api/finance/payflow/settlement'
      preLoaderRoute: typeof ApiFinancePayflowSettlementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/resend/webhook': {
      id: '/api/integrations/resend/webhook'
      path: '/api/integrations/resend/webhook'
      fullPath: '/api/integrations/resend/webhook'
      preLoaderRoute: typeof ApiIntegrationsResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/zoom/callback': {
      id: '/api/integrations/zoom/callback'
      path: '/api/integrations/zoom/callback'
      fullPath: '/api/integrations/zoom/callback'
      preLoaderRoute: typeof ApiIntegrationsZoomCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/domains/check': {
      id: '/api/saas/domains/check'
      path: '/check'
      fullPath: '/api/saas/domains/check'
      preLoaderRoute: typeof ApiSaasDomainsCheckRouteImport
      parentRoute: typeof ApiSaasDomainsRoute
    }
    '/api/saas/domains/poll': {
      id: '/api/saas/domains/poll'
      path: '/poll'
      fullPath: '/api/saas/domains/poll'
      preLoaderRoute: typeof ApiSaasDomainsPollRouteImport
      parentRoute: typeof ApiSaasDomainsRoute
    }
    '/api/saas/domains/status': {
      id: '/api/saas/domains/status'
      path: '/status'
      fullPath: '/api/saas/domains/status'
      preLoaderRoute: typeof ApiSaasDomainsStatusRouteImport
      parentRoute: typeof ApiSaasDomainsRoute
    }
    '/api/saas/domains/verify': {
      id: '/api/saas/domains/verify'
      path: '/verify'
      fullPath: '/api/saas/domains/verify'
      preLoaderRoute: typeof ApiSaasDomainsVerifyRouteImport
      parentRoute: typeof ApiSaasDomainsRoute
    }
    '/api/saas/email/routes': {
      id: '/api/saas/email/routes'
      path: '/api/saas/email/routes'
      fullPath: '/api/saas/email/routes'
      preLoaderRoute: typeof ApiSaasEmailRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saas/platform-admins/revoke': {
      id: '/api/saas/platform-admins/revoke'
      path: '/revoke'
      fullPath: '/api/saas/platform-admins/revoke'
      preLoaderRoute: typeof ApiSaasPlatformAdminsRevokeRouteImport
      parentRoute: typeof ApiSaasPlatformAdminsRoute
    }
    '/api/saas/subscriptions/backfill': {
      id: '/api/saas/subscriptions/backfill'
      path: '/backfill'
      fullPath: '/api/saas/subscriptions/backfill'
      preLoaderRoute: typeof ApiSaasSubscriptionsBackfillRouteImport
      parentRoute: typeof ApiSaasSubscriptionsRoute
    }
    '/api/saas/tenants/lookup': {
      id: '/api/saas/tenants/lookup'
      path: '/lookup'
      fullPath: '/api/saas/tenants/lookup'
      preLoaderRoute: typeof ApiSaasTenantsLookupRouteImport
      parentRoute: typeof ApiSaasTenantsRoute
    }
    '/api/saas/tenants/status': {
      id: '/api/saas/tenants/status'
      path: '/status'
      fullPath: '/api/saas/tenants/status'
      preLoaderRoute: typeof ApiSaasTenantsStatusRouteImport
      parentRoute: typeof ApiSaasTenantsRoute
    }
    '/api/saas/tenants/subscription': {
      id: '/api/saas/tenants/subscription'
      path: '/subscription'
      fullPath: '/api/saas/tenants/subscription'
      preLoaderRoute: typeof ApiSaasTenantsSubscriptionRouteImport
      parentRoute: typeof ApiSaasTenantsRoute
    }
    '/api/saas/usage/sync': {
      id: '/api/saas/usage/sync'
      path: '/api/saas/usage/sync'
      fullPath: '/api/saas/usage/sync'
      preLoaderRoute: typeof ApiSaasUsageSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/finance/gateway/unitel/confirm': {
      id: '/api/finance/gateway/unitel/confirm'
      path: '/api/finance/gateway/unitel/confirm'
      fullPath: '/api/finance/gateway/unitel/confirm'
      preLoaderRoute: typeof ApiFinanceGatewayUnitelConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlumniAlumniIdRouteChildren {
  AlumniAlumniIdPortfolioRoute: typeof AlumniAlumniIdPortfolioRoute
}

const AlumniAlumniIdRouteChildren: AlumniAlumniIdRouteChildren = {
  AlumniAlumniIdPortfolioRoute: AlumniAlumniIdPortfolioRoute,
}

const AlumniAlumniIdRouteWithChildren = AlumniAlumniIdRoute._addFileChildren(
  AlumniAlumniIdRouteChildren,
)

interface AlumniPortalPortfolioRouteChildren {
  AlumniPortalPortfolioEducationRoute: typeof AlumniPortalPortfolioEducationRoute
  AlumniPortalPortfolioPrintRoute: typeof AlumniPortalPortfolioPrintRoute
  AlumniPortalPortfolioShowcaseRoute: typeof AlumniPortalPortfolioShowcaseRoute
}

const AlumniPortalPortfolioRouteChildren: AlumniPortalPortfolioRouteChildren = {
  AlumniPortalPortfolioEducationRoute: AlumniPortalPortfolioEducationRoute,
  AlumniPortalPortfolioPrintRoute: AlumniPortalPortfolioPrintRoute,
  AlumniPortalPortfolioShowcaseRoute: AlumniPortalPortfolioShowcaseRoute,
}

const AlumniPortalPortfolioRouteWithChildren =
  AlumniPortalPortfolioRoute._addFileChildren(
    AlumniPortalPortfolioRouteChildren,
  )

interface AlumniPortalRouteChildren {
  AlumniPortalPortfolioRoute: typeof AlumniPortalPortfolioRouteWithChildren
}

const AlumniPortalRouteChildren: AlumniPortalRouteChildren = {
  AlumniPortalPortfolioRoute: AlumniPortalPortfolioRouteWithChildren,
}

const AlumniPortalRouteWithChildren = AlumniPortalRoute._addFileChildren(
  AlumniPortalRouteChildren,
)

interface AlumniRouteChildren {
  AlumniAlumniIdRoute: typeof AlumniAlumniIdRouteWithChildren
  AlumniCalendarRoute: typeof AlumniCalendarRoute
  AlumniCommunicationsRoute: typeof AlumniCommunicationsRoute
  AlumniDocumentsRoute: typeof AlumniDocumentsRoute
  AlumniInsightsRoute: typeof AlumniInsightsRoute
  AlumniMatchingRoute: typeof AlumniMatchingRoute
  AlumniOperationsRoute: typeof AlumniOperationsRoute
  AlumniPipelineRoute: typeof AlumniPipelineRoute
  AlumniPortalRoute: typeof AlumniPortalRouteWithChildren
}

const AlumniRouteChildren: AlumniRouteChildren = {
  AlumniAlumniIdRoute: AlumniAlumniIdRouteWithChildren,
  AlumniCalendarRoute: AlumniCalendarRoute,
  AlumniCommunicationsRoute: AlumniCommunicationsRoute,
  AlumniDocumentsRoute: AlumniDocumentsRoute,
  AlumniInsightsRoute: AlumniInsightsRoute,
  AlumniMatchingRoute: AlumniMatchingRoute,
  AlumniOperationsRoute: AlumniOperationsRoute,
  AlumniPipelineRoute: AlumniPipelineRoute,
  AlumniPortalRoute: AlumniPortalRouteWithChildren,
}

const AlumniRouteWithChildren =
  AlumniRoute._addFileChildren(AlumniRouteChildren)

interface CalendarioRouteChildren {
  CalendarioIcsRoute: typeof CalendarioIcsRoute
}

const CalendarioRouteChildren: CalendarioRouteChildren = {
  CalendarioIcsRoute: CalendarioIcsRoute,
}

const CalendarioRouteWithChildren = CalendarioRoute._addFileChildren(
  CalendarioRouteChildren,
)

interface FinanceiroRhRouteChildren {
  FinanceiroRhFaltasRoute: typeof FinanceiroRhFaltasRoute
  FinanceiroRhFolhaRoute: typeof FinanceiroRhFolhaRoute
  FinanceiroRhPagamentosRoute: typeof FinanceiroRhPagamentosRoute
  FinanceiroRhPresencaRoute: typeof FinanceiroRhPresencaRoute
  FinanceiroRhSalariosRoute: typeof FinanceiroRhSalariosRoute
}

const FinanceiroRhRouteChildren: FinanceiroRhRouteChildren = {
  FinanceiroRhFaltasRoute: FinanceiroRhFaltasRoute,
  FinanceiroRhFolhaRoute: FinanceiroRhFolhaRoute,
  FinanceiroRhPagamentosRoute: FinanceiroRhPagamentosRoute,
  FinanceiroRhPresencaRoute: FinanceiroRhPresencaRoute,
  FinanceiroRhSalariosRoute: FinanceiroRhSalariosRoute,
}

const FinanceiroRhRouteWithChildren = FinanceiroRhRoute._addFileChildren(
  FinanceiroRhRouteChildren,
)

interface FinanceiroRouteChildren {
  FinanceiroRhRoute: typeof FinanceiroRhRouteWithChildren
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroRhRoute: FinanceiroRhRouteWithChildren,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface ApiSaasDomainsRouteChildren {
  ApiSaasDomainsCheckRoute: typeof ApiSaasDomainsCheckRoute
  ApiSaasDomainsPollRoute: typeof ApiSaasDomainsPollRoute
  ApiSaasDomainsStatusRoute: typeof ApiSaasDomainsStatusRoute
  ApiSaasDomainsVerifyRoute: typeof ApiSaasDomainsVerifyRoute
}

const ApiSaasDomainsRouteChildren: ApiSaasDomainsRouteChildren = {
  ApiSaasDomainsCheckRoute: ApiSaasDomainsCheckRoute,
  ApiSaasDomainsPollRoute: ApiSaasDomainsPollRoute,
  ApiSaasDomainsStatusRoute: ApiSaasDomainsStatusRoute,
  ApiSaasDomainsVerifyRoute: ApiSaasDomainsVerifyRoute,
}

const ApiSaasDomainsRouteWithChildren = ApiSaasDomainsRoute._addFileChildren(
  ApiSaasDomainsRouteChildren,
)

interface ApiSaasPlatformAdminsRouteChildren {
  ApiSaasPlatformAdminsRevokeRoute: typeof ApiSaasPlatformAdminsRevokeRoute
}

const ApiSaasPlatformAdminsRouteChildren: ApiSaasPlatformAdminsRouteChildren = {
  ApiSaasPlatformAdminsRevokeRoute: ApiSaasPlatformAdminsRevokeRoute,
}

const ApiSaasPlatformAdminsRouteWithChildren =
  ApiSaasPlatformAdminsRoute._addFileChildren(
    ApiSaasPlatformAdminsRouteChildren,
  )

interface ApiSaasSubscriptionsRouteChildren {
  ApiSaasSubscriptionsBackfillRoute: typeof ApiSaasSubscriptionsBackfillRoute
}

const ApiSaasSubscriptionsRouteChildren: ApiSaasSubscriptionsRouteChildren = {
  ApiSaasSubscriptionsBackfillRoute: ApiSaasSubscriptionsBackfillRoute,
}

const ApiSaasSubscriptionsRouteWithChildren =
  ApiSaasSubscriptionsRoute._addFileChildren(ApiSaasSubscriptionsRouteChildren)

interface ApiSaasTenantsRouteChildren {
  ApiSaasTenantsLookupRoute: typeof ApiSaasTenantsLookupRoute
  ApiSaasTenantsStatusRoute: typeof ApiSaasTenantsStatusRoute
  ApiSaasTenantsSubscriptionRoute: typeof ApiSaasTenantsSubscriptionRoute
}

const ApiSaasTenantsRouteChildren: ApiSaasTenantsRouteChildren = {
  ApiSaasTenantsLookupRoute: ApiSaasTenantsLookupRoute,
  ApiSaasTenantsStatusRoute: ApiSaasTenantsStatusRoute,
  ApiSaasTenantsSubscriptionRoute: ApiSaasTenantsSubscriptionRoute,
}

const ApiSaasTenantsRouteWithChildren = ApiSaasTenantsRoute._addFileChildren(
  ApiSaasTenantsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessosRoute: AcessosRoute,
  AlterarSenhaRoute: AlterarSenhaRoute,
  AlumniRoute: AlumniRouteWithChildren,
  ArquivosRoute: ArquivosRoute,
  CalendarioRoute: CalendarioRouteWithChildren,
  CatracasRoute: CatracasRoute,
  ComunicacoesRoute: ComunicacoesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CriarEscolaRoute: CriarEscolaRoute,
  DocumentosRoute: DocumentosRoute,
  FaturasRoute: FaturasRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  ImportarRoute: ImportarRoute,
  PedagogicaRoute: PedagogicaRoute,
  PerfilRoute: PerfilRoute,
  PlanosAulaRoute: PlanosAulaRoute,
  SaasAdminRoute: SaasAdminRoute,
  AlunosStudentIdRoute: AlunosStudentIdRoute,
  AuthEmailChangeRoute: AuthEmailChangeRoute,
  AuthMagicLinkRoute: AuthMagicLinkRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  MatriculaSlugRoute: MatriculaSlugRoute,
  ProfessorPresencaRoute: ProfessorPresencaRoute,
  ProfessoresTeacherIdRoute: ProfessoresTeacherIdRoute,
  RelatoriosAcademicosRoute: RelatoriosAcademicosRoute,
  RelatoriosFinanceirosRoute: RelatoriosFinanceirosRoute,
  AlunosIndexRoute: AlunosIndexRoute,
  PessoasIndexRoute: PessoasIndexRoute,
  ApiCalendarIcsRoute: ApiCalendarIcsRoute,
  ApiCatracasDeviceScanRoute: ApiCatracasDeviceScanRoute,
  ApiSaasAuditLogsRoute: ApiSaasAuditLogsRoute,
  ApiSaasDomainsRoute: ApiSaasDomainsRouteWithChildren,
  ApiSaasGatewayWebhooksRoute: ApiSaasGatewayWebhooksRoute,
  ApiSaasMailboxesRoute: ApiSaasMailboxesRoute,
  ApiSaasMeRoute: ApiSaasMeRoute,
  ApiSaasPlansRoute: ApiSaasPlansRoute,
  ApiSaasPlatformAdminsRoute: ApiSaasPlatformAdminsRouteWithChildren,
  ApiSaasSignupRoute: ApiSaasSignupRoute,
  ApiSaasStatsRoute: ApiSaasStatsRoute,
  ApiSaasSubscriptionsRoute: ApiSaasSubscriptionsRouteWithChildren,
  ApiSaasTenantsRoute: ApiSaasTenantsRouteWithChildren,
  ApiWebhooksTwilioSmsRoute: ApiWebhooksTwilioSmsRoute,
  ApiWebhooksWhatsappStatusRoute: ApiWebhooksWhatsappStatusRoute,
  ApiFinanceGatewayConfirmRoute: ApiFinanceGatewayConfirmRoute,
  ApiFinancePayflowSettlementRoute: ApiFinancePayflowSettlementRoute,
  ApiIntegrationsResendWebhookRoute: ApiIntegrationsResendWebhookRoute,
  ApiIntegrationsZoomCallbackRoute: ApiIntegrationsZoomCallbackRoute,
  ApiSaasEmailRoutesRoute: ApiSaasEmailRoutesRoute,
  ApiSaasUsageSyncRoute: ApiSaasUsageSyncRoute,
  ApiFinanceGatewayUnitelConfirmRoute: ApiFinanceGatewayUnitelConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
