// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest, setResponseHeaders } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { assertPublishableSupabaseKey, isOpaqueSupabaseApiKey } from "./api-key";

function unauthorized(reason = "Unauthorized"): never {
  throw Object.assign(new Error(reason), { statusCode: 401 });
}

function decodeAccessTokenClaims(token: string): { sub: string; email?: string } | null {
  try {
    const payload = token.split(".")[1];
    if (!payload) return null;
    const normalized = payload.replaceAll("-", "+").replaceAll("_", "/");
    const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "=");
    const raw =
      typeof globalThis.atob === "function"
        ? globalThis.atob(padded)
        : typeof Buffer !== "undefined"
          ? Buffer.from(padded, "base64").toString("utf8")
          : null;
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { sub?: unknown; email?: unknown; exp?: unknown };
    if (typeof parsed.sub !== "string" || !parsed.sub) return null;
    if (typeof parsed.exp === "number" && parsed.exp * 1000 < Date.now()) return null;
    return {
      sub: parsed.sub,
      email: typeof parsed.email === "string" ? parsed.email : undefined,
    };
  } catch {
    return null;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isOpaqueSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env["SUPABASE_URL"];
    const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    assertPublishableSupabaseKey(SUPABASE_PUBLISHABLE_KEY, "SUPABASE_PUBLISHABLE_KEY");

    const request = getRequest();

    if (!request?.headers) {
      unauthorized("Unauthorized: pedido sem cabeçalhos.");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      unauthorized("Unauthorized: sessão em falta. Termine e volte a entrar.");
    }

    if (!authHeader.startsWith("Bearer ")) {
      unauthorized("Unauthorized: cabeçalho Authorization inválido.");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      unauthorized("Unauthorized: token vazio.");
    }

    if (token.split(".").length !== 3) {
      unauthorized("Unauthorized: token JWT inválido.");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
        detectSessionInUrl: false,
      },
    });

    let authApiError: string | undefined;
    try {
      const { data, error } = await supabase.auth.getClaims(token);
      if (data?.claims?.sub) {
        setResponseHeaders(
          new Headers({
            "Cache-Control": "private, no-store",
            Vary: "Authorization",
          }),
        );
        return next({
          context: {
            supabase,
            userId: data.claims.sub,
            claims: data.claims,
          },
        });
      }
      authApiError = error?.message;
    } catch (claimsError) {
      authApiError = claimsError instanceof Error ? claimsError.message : "getClaims falhou";
    }

    try {
      const { data: userData, error: userError } = await supabase.auth.getUser(token);
      if (userData?.user?.id) {
        setResponseHeaders(
          new Headers({
            "Cache-Control": "private, no-store",
            Vary: "Authorization",
          }),
        );
        return next({
          context: {
            supabase,
            userId: userData.user.id,
            claims: { sub: userData.user.id, email: userData.user.email },
          },
        });
      }
      authApiError = authApiError || userError?.message;
    } catch (userError) {
      authApiError =
        authApiError || (userError instanceof Error ? userError.message : "getUser falhou");
    }

    // Fallback: decode local do JWT quando o Auth API está inacessível no SSR
    // (ex.: "fetch failed"). Handlers usam service role / membership depois disto.
    const localClaims = decodeAccessTokenClaims(token);
    if (localClaims?.sub) {
      setResponseHeaders(
        new Headers({
          "Cache-Control": "private, no-store",
          Vary: "Authorization",
        }),
      );
      return next({
        context: {
          supabase,
          userId: localClaims.sub,
          claims: localClaims,
        },
      });
    }

    unauthorized(`Unauthorized: ${authApiError || "token rejeitado"}.`);
  },
);
