// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest, setResponseHeaders } from "@tanstack/react-start/server";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { assertPublishableSupabaseKey, isOpaqueSupabaseApiKey } from "./api-key";

function unauthorized(reason = "Unauthorized"): never {
  throw Object.assign(new Error(reason), { statusCode: 401 });
}

function decodeAccessTokenClaims(token: string): { sub: string; email?: string } | null {
  try {
    const payload = token.split(".")[1];
    if (!payload) return null;
    const normalized = payload.replaceAll("-", "+").replaceAll("_", "/");
    const padded = normalized.padEnd(Math.ceil(normalized.length / 4) * 4, "=");
    const raw =
      typeof globalThis.atob === "function"
        ? globalThis.atob(padded)
        : typeof Buffer !== "undefined"
          ? Buffer.from(padded, "base64").toString("utf8")
          : null;
    if (!raw) return null;
    const parsed = JSON.parse(raw) as { sub?: unknown; email?: unknown; exp?: unknown };
    if (typeof parsed.sub !== "string" || !parsed.sub) return null;
    if (typeof parsed.exp === "number" && parsed.exp * 1000 < Date.now()) return null;
    return {
      sub: parsed.sub,
      ...(typeof parsed.email === "string" ? { email: parsed.email } : {}),
    };
  } catch {
    return null;
  }
}

async function verifyLocalJwtSignature(token: string, secret: string): Promise<boolean> {
  try {
    const parts = token.split(".");
    if (parts.length !== 3) return false;
    const [headerB64, payloadB64, sigB64] = parts;
    const unsigned = `${headerB64}.${payloadB64}`;

    const normalizedSig = sigB64.replaceAll("-", "+").replaceAll("_", "/");
    const paddedSig = normalizedSig.padEnd(Math.ceil(normalizedSig.length / 4) * 4, "=");
    const sigBytes = Uint8Array.from(atob(paddedSig), (c) => c.charCodeAt(0));

    const key = await crypto.subtle.importKey(
      "raw",
      new TextEncoder().encode(secret),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["verify"],
    );

    return await crypto.subtle.verify("HMAC", key, sigBytes, new TextEncoder().encode(unsigned));
  } catch {
    return false;
  }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isOpaqueSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export type SupabaseAuthContext = {
  supabase: SupabaseClient<Database>;
  userId: string;
  claims: Record<string, unknown> & { sub: string; email?: string };
};

function createAuthContext(
  supabase: SupabaseClient<Database>,
  userId: string,
  rawClaims?: unknown,
): SupabaseAuthContext {
  const claims =
    rawClaims && typeof rawClaims === "object" ? (rawClaims as Record<string, unknown>) : {};
  const email = claims["email"];
  return {
    supabase,
    userId,
    claims: {
      ...claims,
      sub: userId,
      ...(typeof email === "string" ? { email } : {}),
    },
  };
}

export const requireSupabaseAuth = createMiddleware({
  type: "function",
}).server<SupabaseAuthContext>(async ({ next }) => {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY = process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  assertPublishableSupabaseKey(SUPABASE_PUBLISHABLE_KEY, "SUPABASE_PUBLISHABLE_KEY");

  const request = getRequest();

  if (!request?.headers) {
    unauthorized("Unauthorized: pedido sem cabeçalhos.");
  }

  const authHeader = request.headers.get("authorization");

  if (!authHeader) {
    unauthorized("Unauthorized: sessão em falta. Termine e volte a entrar.");
  }

  if (!authHeader.startsWith("Bearer ")) {
    unauthorized("Unauthorized: cabeçalho Authorization inválido.");
  }

  const token = authHeader.replace("Bearer ", "");
  if (!token) {
    unauthorized("Unauthorized: token vazio.");
  }

  if (token.split(".").length !== 3) {
    unauthorized("Unauthorized: token JWT inválido.");
  }

  const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
      headers: {
        Authorization: `Bearer ${token}`,
      },
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
  });

  // `authApiReachable` só fica true quando o Auth API respondeu de facto
  // (mesmo que a rejeitar o token). SEGURANÇA: o fallback de decode local do
  // JWT, mais abaixo, não verifica assinatura — só pode disparar quando o
  // Auth API está genuinamente inacessível (falha de rede no SSR), nunca
  // quando ele respondeu e recusou o token. `getUser`/`getClaims` devolvem
  // `{ data: null, error }` para um token inválido — não lançam — por isso
  // um simples try/catch em torno da chamada não chega para distinguir "API
  // em baixo" de "token forjado/expirado"; sem esta flag, um token com
  // assinatura inválida mas `sub`/`exp` bem formados passava sempre no
  // fallback e dava acesso total via `supabaseAdmin` a jusante.
  let authApiReachable = false;
  let authApiError: string | undefined;
  try {
    const { data, error } = await supabase.auth.getClaims(token);
    authApiReachable = true;
    if (data?.claims?.sub) {
      setResponseHeaders(
        new Headers({
          "Cache-Control": "private, no-store",
          Vary: "Authorization",
        }),
      );
      return next({
        context: createAuthContext(supabase, data.claims.sub, data.claims),
      });
    }
    authApiError = error?.message;
  } catch (claimsError) {
    authApiError = claimsError instanceof Error ? claimsError.message : "getClaims falhou";
  }

  try {
    const { data: userData, error: userError } = await supabase.auth.getUser(token);
    authApiReachable = true;
    if (userData?.user?.id) {
      setResponseHeaders(
        new Headers({
          "Cache-Control": "private, no-store",
          Vary: "Authorization",
        }),
      );
      return next({
        context: createAuthContext(supabase, userData.user.id, { email: userData.user.email }),
      });
    }
    authApiError = authApiError || userError?.message;
  } catch (userError) {
    authApiError =
      authApiError || (userError instanceof Error ? userError.message : "getUser falhou");
  }

  if (authApiReachable) {
    unauthorized(`Unauthorized: ${authApiError || "token rejeitado"}.`);
  }

  // SEGURANÇA (Fail-Closed): Nunca aceitar claims de JWT sem verificação criptográfica da assinatura.
  // Se a API de autenticação da Supabase estiver inacessível no SSR, só aceitar fallback se o
  // SUPABASE_JWT_SECRET estiver configurado e a assinatura HMAC-SHA256 for validada com sucesso.
  const jwtSecret = process.env["SUPABASE_JWT_SECRET"]?.trim();
  if (jwtSecret && jwtSecret.length >= 16) {
    const isValidSignature = await verifyLocalJwtSignature(token, jwtSecret);
    if (isValidSignature) {
      const localClaims = decodeAccessTokenClaims(token);
      if (localClaims?.sub) {
        setResponseHeaders(
          new Headers({
            "Cache-Control": "private, no-store",
            Vary: "Authorization",
          }),
        );
        return next({
          context: createAuthContext(supabase, localClaims.sub, localClaims),
        });
      }
    }
  }

  unauthorized(
    `Unauthorized: ${authApiError || "sessão inválida ou serviço de autenticação indisponível"}.`,
  );
});
