import type { ImportModule } from "../schemas";

export const MODULE_DEMO_ROWS: Record<ImportModule, Array<Record<string, string | number>>> = {
  pessoas: [
    {
      full_name: "Maria Fernanda da Silva",
      national_id: "005432190LA048",
      gender: "F",
      birth_date: "1985-03-22",
      email: "maria.silva@escola.ao",
      phone: "923112233",
      address: "Bairro Benfica, Luanda",
    },
    {
      full_name: "Manuel António Sebastião",
      national_id: "001928374LA033",
      gender: "M",
      birth_date: "1980-07-15",
      email: "manuel.sebastiao@empresa.co.ao",
      phone: "924556677",
      address: "Bairro Morro Bento, Luanda",
    },
    {
      full_name: "Teresa Domingos de Oliveira",
      national_id: "009876543LA099",
      gender: "F",
      birth_date: "1992-11-04",
      email: "teresa.oliveira@escola.ao",
      phone: "931223344",
      address: "Bairro Cidade Alta, Huambo",
    },
    {
      full_name: "António Carlos dos Santos",
      national_id: "004567891HA021",
      gender: "M",
      birth_date: "1988-01-30",
      email: "antonio.santos@escola.ao",
      phone: "912334455",
      address: "Bairro São João, Huambo",
    },
  ],

  alunos: [
    {
      full_name: "João Manuel António",
      student_number: "PROC-2026-042",
      id_number: "005432190LA048",
      gender: "M",
      birth_date: "2012-05-14",
      phone: "923112233",
      email: "joao.antonio@escola.ao",
      guardian_name: "Manuel António Sebastião",
      class_group: "7A",
    },
    {
      full_name: "Benedita Luísa Panzo",
      student_number: "PROC-2026-043",
      id_number: "009123847LA045",
      gender: "F",
      birth_date: "2010-08-19",
      phone: "921887766",
      email: "benedita.panzo@gmail.com",
      guardian_name: "Luísa Domingos Panzo",
      class_group: "10ª Classe A - Manhã",
    },
    {
      full_name: "Daniel Kiala Francisco",
      student_number: "PROC-2026-044",
      id_number: "007234190LA012",
      gender: "M",
      birth_date: "2011-03-10",
      phone: "934556677",
      email: "daniel.francisco@escola.ao",
      guardian_name: "Francisco Kiala",
      class_group: "8B",
    },
    {
      full_name: "Esperança Madalena Dinis",
      student_number: "PROC-2026-045",
      id_number: "008129384HA067",
      gender: "F",
      birth_date: "2009-12-02",
      phone: "945667788",
      email: "esperanca.dinis@escola.ao",
      guardian_name: "Madalena Dinis",
      class_group: "11ª Classe CFB",
    },
  ],

  encarregados: [
    {
      student_identifier: "PROC-2026-042",
      guardian_name: "Manuel António Sebastião",
      id_number: "001928374LA033",
      phone: "924556677",
      email: "manuel.sebastiao@empresa.co.ao",
      relationship_type: "Pai",
      is_financial_responsible: "Sim",
    },
    {
      student_identifier: "PROC-2026-043",
      guardian_name: "Luísa Domingos Panzo",
      id_number: "002819384LA021",
      phone: "921887766",
      email: "luisa.panzo@empresa.co.ao",
      relationship_type: "Mãe",
      is_financial_responsible: "Sim",
    },
    {
      student_identifier: "PROC-2026-044",
      guardian_name: "Francisco Kiala",
      id_number: "003928172LA055",
      phone: "934556677",
      email: "francisco.kiala@gmail.com",
      relationship_type: "Pai",
      is_financial_responsible: "Sim",
    },
    {
      student_identifier: "PROC-2026-045",
      guardian_name: "Madalena Dinis",
      id_number: "004819203HA011",
      phone: "945667788",
      email: "madalena.dinis@hotmail.com",
      relationship_type: "Mãe",
      is_financial_responsible: "Não",
    },
  ],

  professores: [
    {
      full_name: "Maria Fernanda da Silva",
      id_number: "001234567LA032",
      employee_number: "DOC-8921",
      email: "maria.silva@escola.ao",
      phone: "934556677",
      specialty: "Matemática",
      degree: "Licenciatura em Ensino da Matemática",
    },
    {
      full_name: "Paulo Gaspar Baptista",
      id_number: "002345678LA045",
      employee_number: "DOC-8922",
      email: "paulo.baptista@escola.ao",
      phone: "923445566",
      specialty: "Física",
      degree: "Mestrado em Ciências Físicas",
    },
    {
      full_name: "Ana Paula Lourenço",
      id_number: "003456789HA012",
      employee_number: "DOC-8923",
      email: "ana.lourenco@escola.ao",
      phone: "912778899",
      specialty: "Língua Portuguesa",
      degree: "Licenciatura em Linguística",
    },
    {
      full_name: "Domingos Simão Kiala",
      id_number: "004567890BO089",
      employee_number: "DOC-8924",
      email: "domingos.kiala@escola.ao",
      phone: "945112233",
      specialty: "Química",
      degree: "Licenciatura em Química",
    },
  ],

  funcionarios: [
    {
      full_name: "António Carlos dos Santos",
      id_number: "004567891HA021",
      role_title: "Técnico de Secretaria",
      department: "Secretaria Pedagógica",
      phone: "912334455",
      email: "antonio.santos@escola.ao",
      contract_type: "Efectivo",
    },
    {
      full_name: "Suzana Marta Cassoma",
      id_number: "005678902LA099",
      role_title: "Tesoureira Sénior",
      department: "Tesouraria & Contabilidade",
      phone: "923998877",
      email: "suzana.cassoma@escola.ao",
      contract_type: "Efectivo",
    },
    {
      full_name: "Bernardo Filipe Ndala",
      id_number: "006789013HA033",
      role_title: "Assistente de Informática",
      department: "Tecnologias de Informação",
      phone: "931445566",
      email: "bernardo.ndala@escola.ao",
      contract_type: "A Termo",
    },
    {
      full_name: "Isabel Cristina Gouveia",
      id_number: "007890124BO077",
      role_title: "Recepcionista",
      department: "Atendimento & Portaria",
      phone: "942112233",
      email: "isabel.gouveia@escola.ao",
      contract_type: "Efectivo",
    },
  ],

  turmas: [
    {
      code: "10A-M",
      name: "10ª Classe A - Manhã",
      grade_level: "10ª Classe",
      shift: "Manhã",
      room: "Sala 01",
      capacity: 45,
      academic_year: "2026/2027",
    },
    {
      code: "10B-T",
      name: "10ª Classe B - Tarde",
      grade_level: "10ª Classe",
      shift: "Tarde",
      room: "Sala 02",
      capacity: 45,
      academic_year: "2026/2027",
    },
    {
      code: "11A-M",
      name: "11ª Classe A - Manhã",
      grade_level: "11ª Classe",
      shift: "Manhã",
      room: "Sala 03",
      capacity: 40,
      academic_year: "2026/2027",
    },
    {
      code: "7A-M",
      name: "7ª Classe A - Manhã",
      grade_level: "7ª Classe",
      shift: "Manhã",
      room: "Sala 04",
      capacity: 50,
      academic_year: "2026/2027",
    },
  ],

  classes: [
    {
      code: "7",
      name: "7ª Classe",
      course_code: "Ensino Geral",
      cycle: "I Ciclo",
      order_index: 7,
    },
    {
      code: "8",
      name: "8ª Classe",
      course_code: "Ensino Geral",
      cycle: "I Ciclo",
      order_index: 8,
    },
    {
      code: "10-CFB",
      name: "10ª Classe CFB",
      course_code: "CFB",
      cycle: "II Ciclo Geral",
      order_index: 10,
    },
    {
      code: "11-CFB",
      name: "11ª Classe CFB",
      course_code: "CFB",
      cycle: "II Ciclo Geral",
      order_index: 11,
    },
  ],

  cursos: [
    {
      code: "CFB",
      name: "Ciências Físicas e Biológicas",
      academic_level: "Ensino Secundário",
      area: "Ciências Exactas e da Natureza",
      duration_years: 3,
      degree: "Ensino Secundário Geral",
    },
    {
      code: "CCH",
      name: "Ciências Económicas e Jurídicas",
      academic_level: "Ensino Secundário",
      area: "Ciências Sociais e Humanas",
      duration_years: 3,
      degree: "Ensino Secundário Geral",
    },
    {
      code: "INFO",
      name: "Informática de Gestão",
      academic_level: "Ensino Secundário",
      area: "Tecnologias de Informação",
      duration_years: 4,
      degree: "Técnico Médio",
    },
    {
      code: "CONT",
      name: "Contabilidade e Gestão",
      academic_level: "Ensino Secundário",
      area: "Gestão e Administração",
      duration_years: 4,
      degree: "Técnico Médio",
    },
  ],

  disciplinas: [
    {
      code: "MAT",
      name: "Matemática",
      course_code: "CFB",
      grade_level: "10ª Classe",
      workload_hours: 4,
      area: "Ciências Exactas",
    },
    {
      code: "FIS",
      name: "Física",
      course_code: "CFB",
      grade_level: "10ª Classe",
      workload_hours: 3,
      area: "Ciências Exactas",
    },
    {
      code: "QUI",
      name: "Química",
      course_code: "CFB",
      grade_level: "10ª Classe",
      workload_hours: 3,
      area: "Ciências Exactas",
    },
    {
      code: "PORT",
      name: "Língua Portuguesa",
      course_code: "CFB",
      grade_level: "10ª Classe",
      workload_hours: 4,
      area: "Letras e Humanidades",
    },
  ],

  salas: [
    {
      code: "S-01",
      name: "Sala 01 - Bloco Central",
      campus: "Bloco A",
      capacity: 45,
      room_type: "Sala de Aula",
    },
    {
      code: "S-02",
      name: "Sala 02 - Bloco Central",
      campus: "Bloco A",
      capacity: 45,
      room_type: "Sala de Aula",
    },
    {
      code: "LAB-01",
      name: "Laboratório de Informática",
      campus: "Bloco B",
      capacity: 30,
      room_type: "Laboratório",
    },
    {
      code: "ANF-01",
      name: "Anfiteatro Nobre",
      campus: "Edifício Principal",
      capacity: 120,
      room_type: "Anfiteatro",
    },
  ],

  matriculas: [
    {
      student_identifier: "PROC-2026-042",
      class_group: "10ª Classe A - Manhã",
      academic_year: "2026/2027",
      enrollment_date: "2026-02-01",
      status: "active",
    },
    {
      student_identifier: "PROC-2026-043",
      class_group: "10ª Classe A - Manhã",
      academic_year: "2026/2027",
      enrollment_date: "2026-02-01",
      status: "active",
    },
    {
      student_identifier: "PROC-2026-044",
      class_group: "10ª Classe B - Tarde",
      academic_year: "2026/2027",
      enrollment_date: "2026-02-02",
      status: "active",
    },
    {
      student_identifier: "PROC-2026-045",
      class_group: "11ª Classe A - Manhã",
      academic_year: "2026/2027",
      enrollment_date: "2026-02-03",
      status: "active",
    },
  ],

  inscricoes: [
    {
      applicant_name: "Benedita Luísa Panzo",
      id_number: "009123847LA045",
      gender: "F",
      birth_date: "2010-08-19",
      course_choice: "Informática de Gestão",
      grade_level: "10ª Classe",
      phone: "921887766",
      email: "benedita.panzo@gmail.com",
      application_date: "2026-01-15",
    },
    {
      applicant_name: "Kelson Mauro da Costa",
      id_number: "008234190HA012",
      gender: "M",
      birth_date: "2010-11-23",
      course_choice: "Ciências Físicas e Biológicas",
      grade_level: "10ª Classe",
      phone: "933112244",
      email: "kelson.costa@hotmail.com",
      application_date: "2026-01-16",
    },
    {
      applicant_name: "Tatiana Vânia Gomes",
      id_number: "007192834BO099",
      gender: "F",
      birth_date: "2011-02-14",
      course_choice: "Contabilidade e Gestão",
      grade_level: "10ª Classe",
      phone: "912556677",
      email: "tatiana.gomes@gmail.com",
      application_date: "2026-01-18",
    },
    {
      applicant_name: "Álvaro José Vunge",
      id_number: "006928172BE033",
      gender: "M",
      birth_date: "2009-09-05",
      course_choice: "Informática de Gestão",
      grade_level: "10ª Classe",
      phone: "944889900",
      email: "alvaro.vunge@gmail.com",
      application_date: "2026-01-20",
    },
  ],

  horarios: [
    {
      class_group: "10A-M",
      subject: "Matemática",
      teacher_identifier: "001234567LA032",
      weekday: "Segunda-feira",
      start_time: "07:30",
      end_time: "08:15",
      room: "Sala 01",
    },
    {
      class_group: "10A-M",
      subject: "Física",
      teacher_identifier: "002345678LA045",
      weekday: "Segunda-feira",
      start_time: "08:20",
      end_time: "09:05",
      room: "Sala 01",
    },
    {
      class_group: "10A-M",
      subject: "Química",
      teacher_identifier: "004567890BO089",
      weekday: "Terça-feira",
      start_time: "07:30",
      end_time: "08:15",
      room: "Laboratório 01",
    },
    {
      class_group: "10A-M",
      subject: "Língua Portuguesa",
      teacher_identifier: "003456789HA012",
      weekday: "Terça-feira",
      start_time: "08:20",
      end_time: "09:05",
      room: "Sala 01",
    },
  ],

  notas: [
    {
      student_identifier: "005432190LA048",
      subject: "Física",
      term: "1º Trimestre",
      mac: 15,
      npp: 14,
      npt: 16,
    },
    {
      student_identifier: "005432190LA048",
      subject: "Matemática",
      term: "1º Trimestre",
      mac: 14,
      npp: 13,
      npt: 15,
    },
    {
      student_identifier: "009123847LA045",
      subject: "Física",
      term: "1º Trimestre",
      mac: 16,
      npp: 17,
      npt: 16,
    },
    {
      student_identifier: "009123847LA045",
      subject: "Matemática",
      term: "1º Trimestre",
      mac: 17,
      npp: 18,
      npt: 17,
    },
  ],

  avaliacoes: [
    {
      class_group: "10A-M",
      subject: "Química",
      term: "1º Trimestre",
      evaluation_type: "Prova Escrita",
      title: "1ª Prova Parcial de Estequiometria",
      evaluation_date: "2026-03-12",
      max_score: 20,
    },
    {
      class_group: "10A-M",
      subject: "Matemática",
      term: "1º Trimestre",
      evaluation_type: "Mini-Teste",
      title: "Teste Diagnóstico de Álgebra",
      evaluation_date: "2026-03-05",
      max_score: 20,
    },
    {
      class_group: "10A-M",
      subject: "Física",
      term: "1º Trimestre",
      evaluation_type: "Trabalho Prático",
      title: "Relatório de Mecânica Clássica",
      evaluation_date: "2026-03-18",
      max_score: 20,
    },
    {
      class_group: "10A-M",
      subject: "Língua Portuguesa",
      term: "1º Trimestre",
      evaluation_type: "Prova Escrita",
      title: "Prova de Compreensão e Expressão",
      evaluation_date: "2026-03-25",
      max_score: 20,
    },
  ],

  pautas: [
    {
      student_identifier: "PROC-2026-042",
      class_group: "10A-M",
      subject: "Matemática",
      academic_year: "2026/2027",
      annual_average: 14,
      exam_score: 15,
      final_score: 15,
      decision: "Aprovado",
    },
    {
      student_identifier: "PROC-2026-042",
      class_group: "10A-M",
      subject: "Física",
      academic_year: "2026/2027",
      annual_average: 13,
      exam_score: 14,
      final_score: 14,
      decision: "Aprovado",
    },
    {
      student_identifier: "PROC-2026-043",
      class_group: "10A-M",
      subject: "Matemática",
      academic_year: "2026/2027",
      annual_average: 16,
      exam_score: 17,
      final_score: 17,
      decision: "Aprovado",
    },
    {
      student_identifier: "PROC-2026-044",
      class_group: "10A-M",
      subject: "Matemática",
      academic_year: "2026/2027",
      annual_average: 9,
      exam_score: 8,
      final_score: 9,
      decision: "Recurso",
    },
  ],

  presencas: [
    {
      student_identifier: "PROC-2026-042",
      class_group: "10A-M",
      subject: "Língua Portuguesa",
      attendance_date: "2026-03-02",
      status: "Presente",
      reason: "",
    },
    {
      student_identifier: "PROC-2026-042",
      class_group: "10A-M",
      subject: "Matemática",
      attendance_date: "2026-03-02",
      status: "Presente",
      reason: "",
    },
    {
      student_identifier: "PROC-2026-043",
      class_group: "10A-M",
      subject: "Língua Portuguesa",
      attendance_date: "2026-03-02",
      status: "Falta Justificada",
      reason: "Consulta Médica",
    },
    {
      student_identifier: "PROC-2026-044",
      class_group: "10A-M",
      subject: "Língua Portuguesa",
      attendance_date: "2026-03-02",
      status: "Falta Injustificada",
      reason: "",
    },
  ],

  propinas: [
    {
      title: "Propina Mensal - 10ª Classe",
      grade_level: "10ª Classe",
      course: "CFB",
      amount: 35000,
      due_day: 10,
      penalty_rate: 1.5,
    },
    {
      title: "Propina Mensal - 11ª Classe",
      grade_level: "11ª Classe",
      course: "CFB",
      amount: 38000,
      due_day: 10,
      penalty_rate: 1.5,
    },
    {
      title: "Propina Mensal - 12ª Classe",
      grade_level: "12ª Classe",
      course: "CFB",
      amount: 40000,
      due_day: 10,
      penalty_rate: 1.5,
    },
    {
      title: "Transporte Escolar - Rota Benfica/Talatona",
      grade_level: "10ª Classe",
      course: "Todos",
      amount: 25000,
      due_day: 5,
      penalty_rate: 0,
    },
  ],

  pagamentos: [
    {
      student_identifier: "PROC-2026-042",
      month_ref: "Fevereiro 2026",
      amount: 35000,
      payment_date: "2026-02-05",
      payment_method: "Multicaixa Express",
      receipt_number: "MCX-98218921",
    },
    {
      student_identifier: "PROC-2026-043",
      month_ref: "Fevereiro 2026",
      amount: 35000,
      payment_date: "2026-02-06",
      payment_method: "TPA",
      receipt_number: "TPA-00481239",
    },
    {
      student_identifier: "PROC-2026-044",
      month_ref: "Fevereiro 2026",
      amount: 35000,
      payment_date: "2026-02-08",
      payment_method: "Transferência Bancária",
      receipt_number: "BFA-TRF-918231",
    },
    {
      student_identifier: "PROC-2026-045",
      month_ref: "Fevereiro 2026",
      amount: 38000,
      payment_date: "2026-02-09",
      payment_method: "Depósito",
      receipt_number: "DEP-BPC-448120",
    },
  ],

  dividas: [
    {
      student_identifier: "PROC-2026-042",
      invoice_number: "FT-2026/0129",
      month_ref: "Janeiro 2026",
      amount_due: 35000,
      due_date: "2026-01-10",
      status: "Vencido",
    },
    {
      student_identifier: "PROC-2026-043",
      invoice_number: "FT-2026/0130",
      month_ref: "Janeiro 2026",
      amount_due: 35000,
      due_date: "2026-01-10",
      status: "Em Negociação",
    },
    {
      student_identifier: "PROC-2026-044",
      invoice_number: "FT-2026/0131",
      month_ref: "Dezembro 2025",
      amount_due: 35000,
      due_date: "2025-12-10",
      status: "Encaminhado para Cobrança",
    },
    {
      student_identifier: "PROC-2026-045",
      invoice_number: "FT-2026/0132",
      month_ref: "Janeiro 2026",
      amount_due: 38000,
      due_date: "2026-01-10",
      status: "Pendente",
    },
  ],

  historico_academico: [
    {
      student_identifier: "PROC-2026-042",
      academic_year: "2025/2026",
      grade_level: "9ª Classe",
      previous_school: "Complexo Escolar nº 1240 - Huambo",
      final_average: 15.4,
      outcome: "Concluído com Êxito",
    },
    {
      student_identifier: "PROC-2026-043",
      academic_year: "2025/2026",
      grade_level: "9ª Classe",
      previous_school: "Colégio Esperança - Luanda",
      final_average: 16.2,
      outcome: "Concluído com Êxito",
    },
    {
      student_identifier: "PROC-2026-044",
      academic_year: "2025/2026",
      grade_level: "9ª Classe",
      previous_school: "Escola Primária e I Ciclo nº 402 - Benguela",
      final_average: 14.0,
      outcome: "Aprovado",
    },
    {
      student_identifier: "PROC-2026-045",
      academic_year: "2025/2026",
      grade_level: "10ª Classe",
      previous_school: "Instituto Médio Politécnico - Huambo",
      final_average: 13.8,
      outcome: "Transferido",
    },
  ],

  historico_financeiro: [
    {
      student_identifier: "PROC-2026-042",
      academic_year: "2025/2026",
      total_billed: 350000,
      total_paid: 350000,
      balance_due: 0,
      financial_status: "Regularizada",
    },
    {
      student_identifier: "PROC-2026-043",
      academic_year: "2025/2026",
      total_billed: 350000,
      total_paid: 350000,
      balance_due: 0,
      financial_status: "Regularizada",
    },
    {
      student_identifier: "PROC-2026-044",
      academic_year: "2025/2026",
      total_billed: 350000,
      total_paid: 315000,
      balance_due: 35000,
      financial_status: "Pendente",
    },
    {
      student_identifier: "PROC-2026-045",
      academic_year: "2025/2026",
      total_billed: 380000,
      total_paid: 304000,
      balance_due: 76000,
      financial_status: "Com Dívidas",
    },
  ],
};
