import { normalizeText, foldForCompare } from "./normalize";
import type { ImportModule } from "../schemas";

export type FieldDataType = "text" | "date" | "number" | "boolean" | "select" | "email" | "phone";

export interface FieldDefinition {
  key: string;
  label: string;
  description: string;
  type: FieldDataType;
  required: boolean;
  recommended?: boolean;
  aliases: string[];
  options?: string[];
  example?: string;
  transform?: (value: unknown) => unknown;
  validate?: (value: unknown) => string | null;
}

export interface ModuleFieldCatalog {
  module: ImportModule;
  label: string;
  description: string;
  naturalKey: string[];
  fields: FieldDefinition[];
}

/**
 * Catálogo mestre de campos suportados pelo SIGA com regras de aliases
 * abrangentes para tolerância total a planilhas legadas angolanas e internacionais.
 */
export const FIELD_CATALOG: Record<string, ModuleFieldCatalog> = {
  pessoas: {
    module: "pessoas",
    label: "Pessoas & Encarregados",
    description: "Diretório de pessoas físicas, encarregados e contactos da instituição",
    naturalKey: ["national_id", "full_name"],
    fields: [
      {
        key: "full_name",
        label: "Nome Completo",
        description: "Nome completo da pessoa física",
        type: "text",
        required: true,
        example: "Esperança Manuel da Costa",
        aliases: [
          "nome",
          "nome completo",
          "nome da pessoa",
          "pessoa",
          "full name",
          "name",
          "nome_completo",
          "designacao",
          "titular",
        ],
      },
      {
        key: "national_id",
        label: "Bilhete de Identidade / Cédula",
        description: "Número do Bilhete de Identidade (ex: 14 dígitos), Cédula ou Passaporte",
        type: "text",
        required: false,
        recommended: true,
        example: "005432190LA048",
        aliases: [
          "bi",
          "b.i.",
          "b.i",
          "bilhete",
          "bilhete de identidade",
          "n bilhete",
          "no bilhete",
          "num bilhete",
          "cedula",
          "cedula pessoal",
          "passaporte",
          "documento",
          "n documento",
          "numero documento",
          "id number",
          "national id",
          "identificacao",
        ],
      },
      {
        key: "gender",
        label: "Gênero / Sexo",
        description: "Gênero (M para Masculino, F para Feminino)",
        type: "select",
        required: false,
        options: ["M", "F"],
        example: "F",
        aliases: [
          "genero",
          "género",
          "sexo",
          "gender",
          "sex",
          "m_f",
          "m/f",
        ],
      },
      {
        key: "birth_date",
        label: "Data de Nascimento",
        description: "Data de nascimento no formato AAAA-MM-DD",
        type: "date",
        required: false,
        recommended: true,
        example: "1998-05-14",
        aliases: [
          "data de nascimento",
          "data nascimento",
          "nascimento",
          "d.n.",
          "dn",
          "dt nascimento",
          "birth date",
          "dob",
          "data_nasc",
        ],
      },
      {
        key: "phone",
        label: "Telefone / Telemóvel",
        description: "Número de telefone ou telemóvel para contacto",
        type: "phone",
        required: false,
        example: "923123456",
        aliases: [
          "telefone",
          "telemovel",
          "telemóvel",
          "contacto",
          "celular",
          "phone",
          "mobile",
          "tel",
          "whatsapp",
        ],
      },
      {
        key: "email",
        label: "Correio Electrónico (E-mail)",
        description: "Endereço de e-mail institucional ou pessoal",
        type: "email",
        required: false,
        example: "esperanca.costa@escola.ao",
        aliases: [
          "email",
          "e-mail",
          "correio electronico",
          "correio eletrónico",
          "mail",
          "contacto electronico",
        ],
      },
      {
        key: "address",
        label: "Endereço / Residência",
        description: "Endereço residencial, bairro e município",
        type: "text",
        required: false,
        example: "Bairro Morro Bento, Rua 5, Casa 12",
        aliases: [
          "endereco",
          "endereço",
          "residencia",
          "residência",
          "bairro",
          "morada",
          "address",
        ],
      },
    ],
  },
  alunos: {
    module: "alunos",
    label: "Alunos & Estudantes",
    description: "Ficha cadastral de alunos, número de processo e dados de encarregado",
    naturalKey: ["student_number", "id_number", "full_name"],
    fields: [
      {
        key: "full_name",
        label: "Nome Completo do Aluno",
        description: "Nome oficial do estudante para emissão de pautas e certificados",
        type: "text",
        required: true,
        example: "Manuel João da Silva",
        aliases: [
          "nome",
          "nome completo",
          "nome do aluno",
          "nome do estudante",
          "aluno",
          "estudante",
          "student name",
          "full name",
          "nome_aluno",
        ],
      },
      {
        key: "student_number",
        label: "Nº de Processo / Nº Aluno",
        description: "Número de processo escolar único na instituição",
        type: "text",
        required: false,
        recommended: true,
        example: "2026-0042",
        aliases: [
          "n processo",
          "no processo",
          "numero de processo",
          "numero processo",
          "nº processo",
          "processo",
          "n aluno",
          "no aluno",
          "nº aluno",
          "numero aluno",
          "numero do aluno",
          "matricula",
          "n matricula",
          "student number",
          "student id",
          "cod aluno",
          "codigo aluno",
        ],
      },
      {
        key: "id_number",
        label: "Bilhete de Identidade / Cédula",
        description: "Número do BI, Cédula pessoal ou Passaporte",
        type: "text",
        required: false,
        recommended: true,
        example: "006789123LA033",
        aliases: [
          "bi",
          "b.i.",
          "b.i",
          "bilhete",
          "bilhete de identidade",
          "cedula",
          "cedula pessoal",
          "documento",
          "n documento",
          "national id",
        ],
      },
      {
        key: "gender",
        label: "Gênero / Sexo",
        description: "Gênero (M para Masculino, F para Feminino)",
        type: "select",
        required: true,
        options: ["M", "F"],
        example: "M",
        aliases: [
          "genero",
          "género",
          "sexo",
          "gender",
          "sex",
          "m_f",
          "m/f",
        ],
      },
      {
        key: "birth_date",
        label: "Data de Nascimento",
        description: "Data de nascimento (AAAA-MM-DD)",
        type: "date",
        required: false,
        recommended: true,
        example: "2010-08-12",
        aliases: [
          "data de nascimento",
          "data nascimento",
          "nascimento",
          "d.n.",
          "dn",
          "birth date",
          "dob",
        ],
      },
      {
        key: "guardian_name",
        label: "Nome do Encarregado de Educação",
        description: "Nome completo do pai, mãe ou tutor legal",
        type: "text",
        required: false,
        recommended: true,
        example: "António da Silva",
        aliases: [
          "encarregado",
          "nome do encarregado",
          "encarregado de educacao",
          "encarregado de educação",
          "pai",
          "mae",
          "mãe",
          "tutor",
          "responsavel",
          "responsável",
          "guardian",
          "guardian name",
        ],
      },
      {
        key: "guardian_phone",
        label: "Telefone do Encarregado",
        description: "Contacto telefónico principal para avisos e notificações",
        type: "phone",
        required: false,
        recommended: true,
        example: "924112233",
        aliases: [
          "telefone do encarregado",
          "telemovel do encarregado",
          "contacto do encarregado",
          "tel encarregado",
          "guardian phone",
          "telefone encarregado",
        ],
      },
      {
        key: "guardian_relationship",
        label: "Grau de Parentesco",
        description: "Parentesco com o aluno (Pai, Mãe, Tio, Avô, etc.)",
        type: "text",
        required: false,
        example: "Pai",
        aliases: [
          "parentesco",
          "grau de parentesco",
          "relacao",
          "relação",
          "relationship",
        ],
      },
      {
        key: "class_group",
        label: "Turma de Inscrição / Alocação",
        description: "Nome da turma inicial a alocar",
        type: "text",
        required: false,
        recommended: true,
        example: "10ª A Manhã",
        aliases: [
          "turma",
          "nome da turma",
          "turma inicial",
          "class",
          "class group",
          "classe/turma",
        ],
      },
      {
        key: "address",
        label: "Residência / Bairro",
        description: "Localidade ou bairro de residência do aluno",
        type: "text",
        required: false,
        example: "Talatona, Sector 4",
        aliases: [
          "endereco",
          "endereço",
          "residencia",
          "residência",
          "bairro",
          "morada",
        ],
      },
    ],
  },
  professores: {
    module: "professores",
    label: "Professores & Corpo Docente",
    description: "Cadastro de docentes, especialidades e números de agente",
    naturalKey: ["employee_number", "national_id", "full_name"],
    fields: [
      {
        key: "full_name",
        label: "Nome Completo do Docente",
        description: "Nome oficial do professor",
        type: "text",
        required: true,
        example: "Dr. Paulino Afonso Manuel",
        aliases: [
          "nome",
          "nome completo",
          "nome do professor",
          "nome do docente",
          "professor",
          "docente",
          "teacher name",
          "teacher",
        ],
      },
      {
        key: "employee_number",
        label: "Nº de Agente / Registo Docente",
        description: "Número mecânico ou de agente do Ministério da Educação",
        type: "text",
        required: false,
        recommended: true,
        example: "AG-89420",
        aliases: [
          "n agente",
          "no agente",
          "nº agente",
          "numero de agente",
          "agente",
          "n mecanico",
          "numero mecanico",
          "registo",
          "employee number",
          "teacher id",
          "cod professor",
        ],
      },
      {
        key: "national_id",
        label: "Bilhete de Identidade",
        description: "Número do BI nacional",
        type: "text",
        required: false,
        recommended: true,
        example: "001234567LA012",
        aliases: ["bi", "b.i.", "bilhete", "bilhete de identidade", "documento"],
      },
      {
        key: "gender",
        label: "Gênero / Sexo",
        description: "Gênero (M/F)",
        type: "select",
        required: false,
        options: ["M", "F"],
        example: "M",
        aliases: ["genero", "género", "sexo", "gender"],
      },
      {
        key: "phone",
        label: "Telefone de Contacto",
        description: "Contacto telefónico institucional ou móvel",
        type: "phone",
        required: false,
        recommended: true,
        example: "923998877",
        aliases: ["telefone", "telemovel", "contacto", "phone", "mobile"],
      },
      {
        key: "email",
        label: "Correio Electrónico (E-mail)",
        description: "Email de acesso ao portal do professor",
        type: "email",
        required: false,
        recommended: true,
        example: "paulino.manuel@escola.ao",
        aliases: ["email", "e-mail", "mail"],
      },
      {
        key: "specialty",
        label: "Especialidade / Formação",
        description: "Área de especialização (ex: Matemática, Física)",
        type: "text",
        required: false,
        example: "Licenciatura em Ensino da Matemática",
        aliases: [
          "especialidade",
          "formacao",
          "formação",
          "habilitacao",
          "habilitação",
          "area",
          "área",
          "qualificacao",
        ],
      },
    ],
  },
  turmas: {
    module: "turmas",
    label: "Turmas & Salas",
    description: "Estrutura de turmas, salas, turnos e capacidades",
    naturalKey: ["name"],
    fields: [
      {
        key: "name",
        label: "Nome da Turma",
        description: "Designação oficial da turma (ex: 10ª A Manhã)",
        type: "text",
        required: true,
        example: "10ª A Manhã",
        aliases: [
          "nome",
          "nome da turma",
          "turma",
          "designacao",
          "class group",
          "class name",
        ],
      },
      {
        key: "code",
        label: "Código da Turma",
        description: "Código identificador curto",
        type: "text",
        required: false,
        example: "10A-M",
        aliases: ["codigo", "código", "sigla", "code", "cod turma"],
      },
      {
        key: "grade_level",
        label: "Classe / Grau",
        description: "Classe de ensino (ex: 1ª Classe, 10ª Classe)",
        type: "text",
        required: false,
        recommended: true,
        example: "10ª Classe",
        aliases: ["classe", "grau", "ano", "nivel", "nível", "grade level", "grade"],
      },
      {
        key: "shift",
        label: "Turno / Período",
        description: "Turno escolar (Manhã, Tarde, Noite)",
        type: "select",
        required: false,
        options: ["Manhã", "Tarde", "Noite"],
        example: "Manhã",
        aliases: ["turno", "periodo", "período", "shift"],
      },
      {
        key: "room",
        label: "Sala de Aula",
        description: "Designação da sala física",
        type: "text",
        required: false,
        example: "Sala 04",
        aliases: ["sala", "sala de aula", "room", "classroom"],
      },
      {
        key: "capacity",
        label: "Lotação / Capacidade",
        description: "Capacidade máxima de alunos na sala",
        type: "number",
        required: false,
        example: "45",
        aliases: ["capacidade", "lotacao", "lotação", "vagas", "capacity", "max alunos"],
      },
    ],
  },
  matriculas: {
    module: "matriculas",
    label: "Matrículas & Confirmações",
    description: "Vínculo de alunos a turmas no ano lectivo ativo",
    naturalKey: ["student_identifier", "class_group"],
    fields: [
      {
        key: "student_identifier",
        label: "Identificador do Aluno (Nº Processo, BI ou Nome)",
        description: "Processo, documento nacional ou nome para localizar o estudante",
        type: "text",
        required: true,
        example: "2026-0042",
        aliases: [
          "aluno",
          "estudante",
          "n processo",
          "processo",
          "n aluno",
          "bi",
          "identificador",
          "student",
          "student number",
        ],
      },
      {
        key: "class_group",
        label: "Nome da Turma",
        description: "Turma em que o aluno será matriculado",
        type: "text",
        required: true,
        example: "10ª A Manhã",
        aliases: ["turma", "nome da turma", "classe/turma", "class group", "class"],
      },
      {
        key: "enrollment_date",
        label: "Data da Matrícula",
        description: "Data em que foi efectuada a matrícula ou confirmação (AAAA-MM-DD)",
        type: "date",
        required: false,
        example: "2026-01-15",
        aliases: [
          "data de matricula",
          "data matricula",
          "data da matricula",
          "data",
          "enrollment date",
        ],
      },
      {
        key: "status",
        label: "Estado da Matrícula",
        description: "Situação (active / activa, pendente, transferido, cancelada)",
        type: "select",
        required: false,
        options: ["active", "pending", "transferred", "cancelled"],
        example: "active",
        aliases: ["estado", "status", "situacao", "situação"],
      },
    ],
  },
  notas: {
    module: "notas",
    label: "Notas, Pautas & Avaliações",
    description: "Lançamento de notas por disciplina e trimestre na escala de Angola (0-20)",
    naturalKey: ["student_identifier", "subject", "term"],
    fields: [
      {
        key: "student_identifier",
        label: "Identificador do Aluno (Processo ou Nome)",
        description: "Nº de processo, BI ou nome completo do aluno na turma",
        type: "text",
        required: true,
        example: "2026-0042",
        aliases: [
          "aluno",
          "estudante",
          "n processo",
          "processo",
          "n aluno",
          "nome",
          "student",
        ],
      },
      {
        key: "class_group",
        label: "Turma",
        description: "Turma do aluno",
        type: "text",
        required: false,
        recommended: true,
        example: "10ª A Manhã",
        aliases: ["turma", "class group", "class"],
      },
      {
        key: "subject",
        label: "Disciplina / Cadeira",
        description: "Nome ou sigla da disciplina escolar (ex: Matemática, Língua Portuguesa)",
        type: "text",
        required: true,
        example: "Matemática",
        aliases: [
          "disciplina",
          "materia",
          "matéria",
          "cadeira",
          "subject",
          "sigla",
        ],
      },
      {
        key: "term",
        label: "Trimestre / Período",
        description: "Período de avaliação (ex: 1º Trimestre, 2º Trimestre, 3º Trimestre)",
        type: "text",
        required: false,
        recommended: true,
        example: "1º Trimestre",
        aliases: [
          "trimestre",
          "periodo",
          "período",
          "term",
          "epoca",
          "época",
        ],
      },
      {
        key: "mac",
        label: "MAC (Média de Avaliação Contínua)",
        description: "Nota de avaliação contínua (0 a 20)",
        type: "number",
        required: false,
        example: "14.5",
        aliases: ["mac", "continua", "av continua", "avaliacao continua"],
      },
      {
        key: "npp",
        label: "NPP (Nota da Prova do Professor)",
        description: "Nota da prova parcelar do professor (0 a 20)",
        type: "number",
        required: false,
        example: "13.0",
        aliases: ["npp", "prova professor", "prova do professor", "prova de professor", "parcelar", "teste"],
      },
      {
        key: "npt",
        label: "NPT (Nota da Prova Trimestral)",
        description: "Nota da prova trimestral unificada (0 a 20)",
        type: "number",
        required: false,
        example: "15.0",
        aliases: ["npt", "prova trimestral", "prova do trimestre", "trimestral", "exame trimestral"],
      },
      {
        key: "grade",
        label: "Nota / Média Final do Período",
        description: "Classificação final do período no padrão curricular",
        type: "number",
        required: false,
        recommended: true,
        example: "14.2",
        aliases: ["nota", "media", "média", "classificacao", "score", "grade"],
      },
    ],
  },
  disciplinas: {
    module: "disciplinas",
    label: "Disciplinas & Componentes Curriculares",
    description: "Catálogo de disciplinas escolares, siglas e cargas horárias",
    naturalKey: ["code", "name"],
    fields: [
      {
        key: "name",
        label: "Nome da Disciplina",
        description: "Denominação oficial da disciplina curricular",
        type: "text",
        required: true,
        example: "Matemática",
        aliases: ["disciplina", "nome disciplina", "nome da disciplina", "materia", "subject", "subject name"],
      },
      {
        key: "code",
        label: "Código / Sigla",
        description: "Abreviatura ou código identificador único",
        type: "text",
        required: false,
        recommended: true,
        example: "MAT",
        aliases: ["codigo", "código", "sigla", "code", "abreviatura", "abreviacao", "short name"],
      },
      {
        key: "workload_hours",
        label: "Carga Horária (Horas Semanais)",
        description: "Número de tempos lectivos ou horas semanais",
        type: "number",
        required: false,
        example: "4",
        aliases: ["carga horaria", "carga horária", "tempos", "horas", "workload", "horas semanais"],
      },
    ],
  },
  cursos: {
    module: "cursos",
    label: "Cursos & Especialidades",
    description: "Cursos ministrados pela instituição de ensino",
    naturalKey: ["code", "name"],
    fields: [
      {
        key: "name",
        label: "Nome do Curso",
        description: "Nome oficial do curso ou ramo de formação",
        type: "text",
        required: true,
        example: "Ciências Físicas e Biológicas",
        aliases: ["curso", "nome curso", "nome do curso", "course", "course name"],
      },
      {
        key: "code",
        label: "Código do Curso",
        description: "Identificador ou sigla do curso",
        type: "text",
        required: false,
        example: "CFB",
        aliases: ["codigo curso", "sigla curso", "course code"],
      },
      {
        key: "duration_years",
        label: "Duração (Anos)",
        description: "Duração em anos lectivos",
        type: "number",
        required: false,
        example: "3",
        aliases: ["duracao", "duração", "anos", "duration"],
      },
    ],
  },
  pagamentos: {
    module: "pagamentos",
    label: "Pagamentos & Cobrança de Propinas",
    description: "Registo de faturas, propinas e mensalidades pagas",
    naturalKey: ["invoice_number"],
    fields: [
      {
        key: "student_number",
        label: "Nº de Processo do Aluno",
        description: "Número de processo ou matrícula do estudante",
        type: "text",
        required: true,
        example: "2026-0001",
        aliases: ["processo", "n processo", "nº processo", "aluno", "student id", "student number"],
      },
      {
        key: "amount",
        label: "Valor da Fatura / Mensalidade (AOA)",
        description: "Quantia total faturada em Kwanzas",
        type: "number",
        required: true,
        example: "35000.00",
        aliases: ["valor", "propina", "mensalidade", "amount", "total", "preco", "preço"],
      },
      {
        key: "amount_paid",
        label: "Valor Liquidado / Pago (AOA)",
        description: "Quantia efetivamente paga pelo encarregado",
        type: "number",
        required: false,
        example: "35000.00",
        aliases: ["pago", "valor pago", "liquidado", "amount paid"],
      },
      {
        key: "due_date",
        label: "Data de Vencimento",
        description: "Prazo limite para liquidação (AAAA-MM-DD)",
        type: "date",
        required: false,
        example: "2026-03-10",
        aliases: ["vencimento", "data vencimento", "data de vencimento", "due date"],
      },
      {
        key: "payment_channel",
        label: "Canal / Forma de Pagamento",
        description: "Forma de pagamento (Multicaixa, Transferência, Depósito, Dinheiro, Unitel Money)",
        type: "select",
        options: ["Multicaixa", "Transferência", "Depósito", "Dinheiro", "Unitel Money"],
        required: false,
        example: "Multicaixa",
        aliases: ["canal", "forma pagamento", "modo pagamento", "metodo", "payment method"],
      },
    ],
  },
  encarregados: {
    module: "encarregados",
    label: "Encarregados de Educação",
    description: "Associação e contactos de pais, mães e tutores legais dos educandos",
    naturalKey: ["student_identifier", "guardian_name"],
    fields: [
      {
        key: "student_identifier",
        label: "Aluno (Processo ou BI)",
        description: "Nº de Processo ou BI do educando",
        type: "text",
        required: true,
        example: "PROC-2026-042",
        aliases: ["aluno", "processo", "bi aluno", "estudante", "student id", "student identifier"],
      },
      {
        key: "guardian_name",
        label: "Nome do Encarregado",
        description: "Nome completo do encarregado de educação",
        type: "text",
        required: true,
        example: "Manuel António Sebastião",
        aliases: ["encarregado", "nome encarregado", "nome do encarregado", "tutor", "responsavel", "pai", "mae"],
      },
      {
        key: "id_number",
        label: "BI do Encarregado",
        description: "Bilhete de identidade do encarregado",
        type: "text",
        required: false,
        example: "001928374LA033",
        aliases: ["bi encarregado", "bi do encarregado", "documento encarregado", "nif encarregado", "national id"],
      },
      {
        key: "phone",
        label: "Telefone do Encarregado",
        description: "Telefone principal de contacto",
        type: "phone",
        required: true,
        example: "924556677",
        aliases: ["telefone", "telemovel", "contacto", "telefone encarregado", "tel", "phone"],
      },
      {
        key: "email",
        label: "E-mail do Encarregado",
        description: "E-mail para avisos e faturas",
        type: "email",
        required: false,
        example: "manuel.sebastiao@empresa.co.ao",
        aliases: ["email", "correio", "email encarregado"],
      },
      {
        key: "relationship_type",
        label: "Grau de Parentesco",
        description: "Pai, Mãe, Tutor, Tio, Avô ou Encarregado Legal",
        type: "select",
        options: ["Pai", "Mãe", "Tutor", "Tio", "Avô", "Encarregado Legal"],
        required: false,
        example: "Pai",
        aliases: ["parentesco", "grau parentesco", "relacao", "tipo relacao", "relationship"],
      },
      {
        key: "is_financial_responsible",
        label: "Responsável Financeiro",
        description: "Indica se é o responsável pelas propinas (Sim / Não)",
        type: "select",
        options: ["Sim", "Não"],
        required: false,
        example: "Sim",
        aliases: ["responsavel financeiro", "paga propinas", "financeiro", "financial responsible"],
      },
    ],
  },
  funcionarios: {
    module: "funcionarios",
    label: "Funcionários Administrativos",
    description: "Colaboradores da administração, secretaria, tesouraria e serviços gerais",
    naturalKey: ["id_number", "full_name"],
    fields: [
      {
        key: "full_name",
        label: "Nome Completo",
        description: "Nome completo do colaborador",
        type: "text",
        required: true,
        example: "António Carlos dos Santos",
        aliases: ["nome", "nome completo", "funcionario", "colaborador", "trabalhador"],
      },
      {
        key: "id_number",
        label: "Nº BI / Documento",
        description: "Bilhete de Identidade do funcionário",
        type: "text",
        required: true,
        example: "004567891HA021",
        aliases: ["bi", "documento", "n bi", "identificacao", "id number", "national id"],
      },
      {
        key: "role_title",
        label: "Cargo / Função",
        description: "Secretário, Tesoureiro, Porteiro, Técnico TI, etc.",
        type: "text",
        required: true,
        example: "Técnico de Secretaria",
        aliases: ["cargo", "funcao", "função", "ocupacao", "posicao", "role"],
      },
      {
        key: "department",
        label: "Departamento / Sector",
        description: "Secretaria, Tesouraria, Direcção, Serviços Gerais",
        type: "text",
        required: false,
        example: "Secretaria Pedagógica",
        aliases: ["departamento", "sector", "seccao", "área", "department"],
      },
      {
        key: "phone",
        label: "Telefone",
        description: "Telefone de contacto",
        type: "phone",
        required: true,
        example: "912334455",
        aliases: ["telefone", "contacto", "telemovel", "phone"],
      },
      {
        key: "email",
        label: "E-mail",
        description: "Correio eletrónico institucional ou pessoal",
        type: "email",
        required: false,
        example: "antonio.santos@escola.ao",
        aliases: ["email", "correio"],
      },
      {
        key: "contract_type",
        label: "Tipo de Contrato",
        description: "Efectivo, A Termo, Estagiário, Prestação de Serviços",
        type: "select",
        options: ["Efectivo", "A Termo", "Estagiário", "Prestação de Serviços"],
        required: false,
        example: "Efectivo",
        aliases: ["contrato", "tipo contrato", "vinculo", "regime"],
      },
    ],
  },
  classes: {
    module: "classes",
    label: "Classes & Graus de Ensino",
    description: "Estrutura dos anos de escolaridade e graus curriculares",
    naturalKey: ["code", "name"],
    fields: [
      {
        key: "code",
        label: "Código da Classe",
        description: "Identificador curto da classe (ex.: 7, 8, 10-CFB)",
        type: "text",
        required: true,
        example: "10-CFB",
        aliases: ["codigo", "sigla", "classe", "nivel", "code"],
      },
      {
        key: "name",
        label: "Nome da Classe",
        description: "Nome completo da classe (ex.: 10ª Classe)",
        type: "text",
        required: true,
        example: "10ª Classe",
        aliases: ["nome classe", "designacao", "classe nome", "grau", "name"],
      },
      {
        key: "course_code",
        label: "Curso / Especialidade",
        description: "Código ou nome do curso associado",
        type: "text",
        required: false,
        example: "CFB",
        aliases: ["curso", "sigla curso", "ramo", "course"],
      },
      {
        key: "cycle",
        label: "Ciclo de Ensino",
        description: "Primário, I Ciclo, II Ciclo Técnico, II Ciclo Geral",
        type: "text",
        required: false,
        example: "II Ciclo Geral",
        aliases: ["ciclo", "ciclo de ensino", "grau escolar", "etapa"],
      },
      {
        key: "order_index",
        label: "Ordem / Nível",
        description: "Ordem sequencial numérica da classe (ex.: 10)",
        type: "number",
        required: false,
        example: "10",
        aliases: ["ordem", "sequencia", "ano curricular", "order"],
      },
    ],
  },
  salas: {
    module: "salas",
    label: "Salas & Infraestruturas",
    description: "Espaços físicos, laboratórios, salas de aula e pavilhões",
    naturalKey: ["code", "name"],
    fields: [
      {
        key: "code",
        label: "Código da Sala",
        description: "Código identificador (ex.: S-01, LAB-INFO)",
        type: "text",
        required: true,
        example: "S-01",
        aliases: ["sala", "codigo sala", "numero sala", "espaco", "room code"],
      },
      {
        key: "name",
        label: "Nome da Sala",
        description: "Designação da sala ou espaço",
        type: "text",
        required: true,
        example: "Sala 01 - Bloco Central",
        aliases: ["nome sala", "designacao", "sala nome", "descricao", "name"],
      },
      {
        key: "campus",
        label: "Campus / Bloco",
        description: "Identificação do campus ou bloco físico",
        type: "text",
        required: false,
        example: "Bloco A",
        aliases: ["bloco", "campus", "edificio", "pavilhao", "ala"],
      },
      {
        key: "capacity",
        label: "Capacidade",
        description: "Lotação máxima de carteiras",
        type: "number",
        required: false,
        example: "40",
        aliases: ["capacidade", "lotacao", "carteiras", "lugares", "capacity"],
      },
      {
        key: "room_type",
        label: "Tipo de Espaço",
        description: "Sala de Aula, Laboratório, Anfiteatro, Pavilhão",
        type: "select",
        options: ["Sala de Aula", "Laboratório", "Anfiteatro", "Pavilhão", "Oficina"],
        required: false,
        example: "Sala de Aula",
        aliases: ["tipo sala", "tipo espaco", "finalidade", "categoria"],
      },
    ],
  },
  inscricoes: {
    module: "inscricoes",
    label: "Inscrições & Candidaturas",
    description: "Registo de novos ingressos e candidaturas de novos alunos",
    naturalKey: ["id_number", "applicant_name"],
    fields: [
      {
        key: "applicant_name",
        label: "Nome do Candidato",
        description: "Nome completo do candidato",
        type: "text",
        required: true,
        example: "Benedita Luísa Panzo",
        aliases: ["candidato", "nome candidato", "inscrito", "nome", "applicant"],
      },
      {
        key: "id_number",
        label: "Nº BI / Cédula",
        description: "Documento de identificação do candidato",
        type: "text",
        required: true,
        example: "009123847LA045",
        aliases: ["bi", "cedula", "documento", "id number", "national id"],
      },
      {
        key: "gender",
        label: "Gênero",
        description: "M ou F",
        type: "select",
        options: ["M", "F"],
        required: true,
        example: "F",
        aliases: ["genero", "género", "sexo"],
      },
      {
        key: "birth_date",
        label: "Data de Nascimento",
        description: "AAAA-MM-DD",
        type: "date",
        required: true,
        example: "2010-08-19",
        aliases: ["data nascimento", "nascimento", "birth date"],
      },
      {
        key: "course_choice",
        label: "Curso Pretendido",
        description: "Curso ou especialidade pretendida",
        type: "text",
        required: false,
        example: "Informática de Gestão",
        aliases: ["curso", "curso pretendido", "opcao curso", "curso escolha"],
      },
      {
        key: "grade_level",
        label: "Classe Pretendida",
        description: "Classe a ingressar (ex: 10ª Classe, 7ª Classe)",
        type: "text",
        required: true,
        example: "10ª Classe",
        aliases: ["classe", "classe pretendida", "ano pretendido"],
      },
      {
        key: "phone",
        label: "Telefone de Contacto",
        description: "Telefone do encarregado ou candidato",
        type: "phone",
        required: true,
        example: "921887766",
        aliases: ["telefone", "contacto", "telemovel", "phone"],
      },
      {
        key: "email",
        label: "E-mail",
        description: "Correio eletrónico de contacto",
        type: "email",
        required: false,
        example: "benedita.panzo@gmail.com",
        aliases: ["email", "correio"],
      },
      {
        key: "application_date",
        label: "Data de Inscrição",
        description: "Data de entrega da candidatura (AAAA-MM-DD)",
        type: "date",
        required: false,
        example: "2026-01-15",
        aliases: ["data inscricao", "data candidatura", "data", "application date"],
      },
    ],
  },
  horarios: {
    module: "horarios",
    label: "Horários Escolares",
    description: "Matriz semanal de tempos lectivos por turma e docente",
    naturalKey: ["class_group", "weekday", "start_time"],
    fields: [
      {
        key: "class_group",
        label: "Turma",
        description: "Código ou nome da turma",
        type: "text",
        required: true,
        example: "10A-M",
        aliases: ["turma", "codigo turma", "class group"],
      },
      {
        key: "subject",
        label: "Disciplina",
        description: "Sigla ou nome da disciplina",
        type: "text",
        required: true,
        example: "Matemática",
        aliases: ["disciplina", "materia", "subject"],
      },
      {
        key: "teacher_identifier",
        label: "Professor (Nº Agente ou BI)",
        description: "Docente responsável pela aula",
        type: "text",
        required: false,
        example: "001234567LA032",
        aliases: ["professor", "docente", "agente", "docente nome", "teacher"],
      },
      {
        key: "weekday",
        label: "Dia da Semana",
        description: "Segunda-feira a Sábado",
        type: "select",
        options: ["Segunda-feira", "Terça-feira", "Quarta-feira", "Quinta-feira", "Sexta-feira", "Sábado"],
        required: true,
        example: "Segunda-feira",
        aliases: ["dia", "dia semana", "dia da semana", "weekday"],
      },
      {
        key: "start_time",
        label: "Hora de Início",
        description: "Formato HH:MM (ex.: 07:30)",
        type: "text",
        required: true,
        example: "07:30",
        aliases: ["inicio", "hora inicio", "entrada", "start time"],
      },
      {
        key: "end_time",
        label: "Hora de Fim",
        description: "Formato HH:MM (ex.: 08:15)",
        type: "text",
        required: true,
        example: "08:15",
        aliases: ["fim", "hora fim", "saida", "end time"],
      },
      {
        key: "room",
        label: "Sala",
        description: "Sala de realização da aula",
        type: "text",
        required: false,
        example: "Sala 04",
        aliases: ["sala", "espaco", "room"],
      },
    ],
  },
  avaliacoes: {
    module: "avaliacoes",
    label: "Instrumentos de Avaliação",
    description: "Agendamento e especificações de provas, testes e trabalhos",
    naturalKey: ["class_group", "subject", "term", "title"],
    fields: [
      {
        key: "class_group",
        label: "Turma",
        description: "Turma avaliada",
        type: "text",
        required: true,
        example: "10A-M",
        aliases: ["turma", "class group"],
      },
      {
        key: "subject",
        label: "Disciplina",
        description: "Disciplina curricular",
        type: "text",
        required: true,
        example: "Química",
        aliases: ["disciplina", "subject"],
      },
      {
        key: "term",
        label: "Trimestre / Período",
        description: "1º Trimestre, 2º Trimestre ou 3º Trimestre",
        type: "text",
        required: true,
        example: "1º Trimestre",
        aliases: ["trimestre", "periodo", "term"],
      },
      {
        key: "evaluation_type",
        label: "Tipo de Instrumento",
        description: "Prova Escrita, Trabalho Prático, Mini-Teste, Oral",
        type: "select",
        options: ["Prova Escrita", "Trabalho Prático", "Mini-Teste", "Oral", "Projeto"],
        required: true,
        example: "Prova Escrita",
        aliases: ["tipo avaliacao", "instrumento", "tipo prova", "evaluation type"],
      },
      {
        key: "title",
        label: "Título da Avaliação",
        description: "Descrição da prova ou teste",
        type: "text",
        required: true,
        example: "1ª Prova Parcial de Estequiometria",
        aliases: ["titulo", "descricao avaliacao", "prova", "title"],
      },
      {
        key: "evaluation_date",
        label: "Data de Aplicação",
        description: "Data de realização da prova",
        type: "date",
        required: false,
        example: "2026-03-12",
        aliases: ["data avaliacao", "data prova", "data", "date"],
      },
      {
        key: "max_score",
        label: "Cotação Máxima",
        description: "Escala máxima (padrão 20)",
        type: "number",
        required: false,
        example: "20",
        aliases: ["cotacao", "cotacao maxima", "valor maximo", "escala"],
      },
    ],
  },
  pautas: {
    module: "pautas",
    label: "Pautas Oficiais & Resultados Finais",
    description: "Resultados anuais consolidados, CAP, Exames e decisão do conselho de notas",
    naturalKey: ["student_identifier", "class_group", "subject"],
    fields: [
      {
        key: "student_identifier",
        label: "Aluno (Processo ou BI)",
        description: "Número do processo ou bilhete de identidade",
        type: "text",
        required: true,
        example: "PROC-2026-042",
        aliases: ["aluno", "processo", "bi", "student id"],
      },
      {
        key: "class_group",
        label: "Turma",
        description: "Turma oficial",
        type: "text",
        required: true,
        example: "10A-M",
        aliases: ["turma", "class group"],
      },
      {
        key: "subject",
        label: "Disciplina",
        description: "Disciplina avaliada",
        type: "text",
        required: true,
        example: "Matemática",
        aliases: ["disciplina", "subject"],
      },
      {
        key: "academic_year",
        label: "Ano Lectivo",
        description: "Ano lectivo de referência",
        type: "text",
        required: true,
        example: "2026/2027",
        aliases: ["ano lectivo", "ano letivo", "ano"],
      },
      {
        key: "annual_average",
        label: "Média Anual (CAP)",
        description: "Classificação Anual Pedagógica (0 a 20)",
        type: "number",
        required: true,
        example: "14",
        aliases: ["cap", "media anual", "media pedagogica", "media"],
      },
      {
        key: "exam_score",
        label: "Exame Final (CNE)",
        description: "Classificação da Prova ou Exame Nacional",
        type: "number",
        required: false,
        example: "15",
        aliases: ["cne", "nota exame", "exame", "prova final"],
      },
      {
        key: "final_score",
        label: "Classificação Final (CFD)",
        description: "Classificação Final da Disciplina (0 a 20)",
        type: "number",
        required: true,
        example: "15",
        aliases: ["cfd", "nota final", "classificacao final", "cf"],
      },
      {
        key: "decision",
        label: "Decisão / Resultado",
        description: "Aprovado, Recurso, Reprovado",
        type: "select",
        options: ["Aprovado", "Recurso", "Reprovado"],
        required: true,
        example: "Aprovado",
        aliases: ["decisao", "resultado", "situacao", "desfecho", "status final"],
      },
    ],
  },
  presencas: {
    module: "presencas",
    label: "Faltas & Presenças",
    description: "Controlo diário de assiduidade por aluno, turma e disciplina",
    naturalKey: ["student_identifier", "class_group", "attendance_date"],
    fields: [
      {
        key: "student_identifier",
        label: "Aluno (Processo ou BI)",
        description: "Identificação do estudante",
        type: "text",
        required: true,
        example: "PROC-2026-042",
        aliases: ["aluno", "processo", "bi", "student id"],
      },
      {
        key: "class_group",
        label: "Turma",
        description: "Turma frequentada",
        type: "text",
        required: true,
        example: "10A-M",
        aliases: ["turma", "class group"],
      },
      {
        key: "subject",
        label: "Disciplina",
        description: "Disciplina da aula",
        type: "text",
        required: true,
        example: "Língua Portuguesa",
        aliases: ["disciplina", "subject"],
      },
      {
        key: "attendance_date",
        label: "Data da Aula",
        description: "Data lectiva (AAAA-MM-DD)",
        type: "date",
        required: true,
        example: "2026-03-02",
        aliases: ["data", "data aula", "dia", "attendance date"],
      },
      {
        key: "status",
        label: "Estado da Presença",
        description: "Presente, Falta Justificada, Falta Injustificada, Atraso",
        type: "select",
        options: ["Presente", "Falta Justificada", "Falta Injustificada", "Atraso"],
        required: true,
        example: "Presente",
        aliases: ["estado", "presenca", "falta", "status"],
      },
      {
        key: "reason",
        label: "Motivo / Justificação",
        description: "Motivo de saúde, declaração médica, etc.",
        type: "text",
        required: false,
        example: "Consulta Médica",
        aliases: ["motivo", "justificacao", "observacao", "reason"],
      },
    ],
  },
  propinas: {
    module: "propinas",
    label: "Tabela & Preçário de Propinas",
    description: "Valores mensais de propinas, datas limite e multas",
    naturalKey: ["title", "grade_level"],
    fields: [
      {
        key: "title",
        label: "Designação da Propina / Serviço",
        description: "Ex.: Propina Mensal 10ª Classe, Transporte Escolar",
        type: "text",
        required: true,
        example: "Propina Mensal - 10ª Classe",
        aliases: ["propina", "descricao", "designacao", "servico", "mensalidade"],
      },
      {
        key: "grade_level",
        label: "Classe Aplicável",
        description: "Classe ou grau destinatário",
        type: "text",
        required: true,
        example: "10ª Classe",
        aliases: ["classe", "grau", "nivel", "grade level"],
      },
      {
        key: "course",
        label: "Curso Aplicável",
        description: "Curso específico ou Todos",
        type: "text",
        required: false,
        example: "CFB",
        aliases: ["curso", "especialidade", "course"],
      },
      {
        key: "amount",
        label: "Valor Mensal (Kz)",
        description: "Quantia oficial em Kwanzas",
        type: "number",
        required: true,
        example: "35000",
        aliases: ["valor", "preco", "montante", "propina mensal", "amount"],
      },
      {
        key: "due_day",
        label: "Dia Limite de Pagamento",
        description: "Dia do mês limite sem multa (ex.: 10)",
        type: "number",
        required: false,
        example: "10",
        aliases: ["dia limite", "vencimento dia", "dia vencimento", "due day"],
      },
      {
        key: "penalty_rate",
        label: "Taxa de Multa Diária (%)",
        description: "Percentagem de mora após o vencimento",
        type: "number",
        required: false,
        example: "1.5",
        aliases: ["multa", "taxa multa", "juros mora", "penalty"],
      },
    ],
  },
  dividas: {
    module: "dividas",
    label: "Dívidas & Faturas em Atraso",
    description: "Pendências financeiras e valores vencidos por regularizar",
    naturalKey: ["student_identifier", "month_ref"],
    fields: [
      {
        key: "student_identifier",
        label: "Aluno (Processo ou BI)",
        description: "Aluno devedor",
        type: "text",
        required: true,
        example: "PROC-2026-042",
        aliases: ["aluno", "processo", "bi", "student id"],
      },
      {
        key: "invoice_number",
        label: "Nº da Fatura / Guia",
        description: "Número do documento de cobrança",
        type: "text",
        required: false,
        example: "FT-2026/0129",
        aliases: ["fatura", "guia", "documento", "recibo", "invoice"],
      },
      {
        key: "month_ref",
        label: "Mês / Descrição da Dívida",
        description: "Mês ou serviço em incumprimento",
        type: "text",
        required: true,
        example: "Janeiro 2026",
        aliases: ["mes", "referencia", "descricao", "month ref"],
      },
      {
        key: "amount_due",
        label: "Valor em Dívida (Kz)",
        description: "Montante em mora em Kwanzas",
        type: "number",
        required: true,
        example: "35000",
        aliases: ["valor divida", "em atraso", "montante divida", "saldo", "amount due"],
      },
      {
        key: "due_date",
        label: "Data de Vencimento",
        description: "Prazo original de pagamento (AAAA-MM-DD)",
        type: "date",
        required: true,
        example: "2026-01-10",
        aliases: ["data vencimento", "vencimento", "due date"],
      },
      {
        key: "status",
        label: "Estado da Cobrança",
        description: "Pendente, Vencido, Em Negociação",
        type: "select",
        options: ["Pendente", "Vencido", "Em Negociação", "Encaminhado para Cobrança"],
        required: false,
        example: "Vencido",
        aliases: ["estado", "situacao divida", "status"],
      },
    ],
  },
  historico_academico: {
    module: "historico_academico",
    label: "Histórico Escolar Anterior",
    description: "Registo de anos escolares anteriores e escolas de proveniência",
    naturalKey: ["student_identifier", "academic_year"],
    fields: [
      {
        key: "student_identifier",
        label: "Aluno (Processo ou BI)",
        description: "Aluno no SIGA",
        type: "text",
        required: true,
        example: "PROC-2026-042",
        aliases: ["aluno", "processo", "bi", "student id"],
      },
      {
        key: "academic_year",
        label: "Ano Lectivo Anterior",
        description: "Ano em que frequentou o nível",
        type: "text",
        required: true,
        example: "2025/2026",
        aliases: ["ano lectivo", "ano anterior", "ano"],
      },
      {
        key: "grade_level",
        label: "Classe Frequentada",
        description: "Classe de origem (ex.: 9ª Classe)",
        type: "text",
        required: true,
        example: "9ª Classe",
        aliases: ["classe", "grau", "nivel"],
      },
      {
        key: "previous_school",
        label: "Escola de Proveniência",
        description: "Nome do colégio ou escola pública anterior",
        type: "text",
        required: false,
        example: "Complexo Escolar nº 1240 - Huambo",
        aliases: ["escola anterior", "proveniencia", "colegio de origem", "origem"],
      },
      {
        key: "final_average",
        label: "Média Final Obtida",
        description: "Média de conclusão do ano (0 a 20)",
        type: "number",
        required: false,
        example: "15.4",
        aliases: ["media final", "media conclusao", "media"],
      },
      {
        key: "outcome",
        label: "Desfecho / Resultado",
        description: "Concluído com Êxito, Transferido, Aprovado",
        type: "select",
        options: ["Concluído com Êxito", "Transferido", "Aprovado"],
        required: true,
        example: "Concluído com Êxito",
        aliases: ["resultado", "desfecho", "conclusao", "outcome"],
      },
    ],
  },
  historico_financeiro: {
    module: "historico_financeiro",
    label: "Histórico Financeiro por Aluno",
    description: "Balanço consolidado anual de faturação e liquidações por estudante",
    naturalKey: ["student_identifier", "academic_year"],
    fields: [
      {
        key: "student_identifier",
        label: "Aluno (Processo ou BI)",
        description: "Identificação do estudante",
        type: "text",
        required: true,
        example: "PROC-2026-042",
        aliases: ["aluno", "processo", "bi", "student id"],
      },
      {
        key: "academic_year",
        label: "Ano Lectivo",
        description: "Ano do balanço financeiro",
        type: "text",
        required: true,
        example: "2025/2026",
        aliases: ["ano lectivo", "ano"],
      },
      {
        key: "total_billed",
        label: "Total Faturado no Ano (Kz)",
        description: "Soma de todas as mensalidades e serviços emitidos",
        type: "number",
        required: true,
        example: "350000",
        aliases: ["total faturado", "total emitido", "faturado", "billed"],
      },
      {
        key: "total_paid",
        label: "Total Liquidado / Pago (Kz)",
        description: "Soma de todos os pagamentos validados",
        type: "number",
        required: true,
        example: "350000",
        aliases: ["total pago", "total liquidado", "liquidado", "paid"],
      },
      {
        key: "balance_due",
        label: "Saldo Devedor Residual (Kz)",
        description: "Valor pendente (0 se regularizado)",
        type: "number",
        required: false,
        example: "0",
        aliases: ["saldo devedor", "em divida", "saldo", "balance"],
      },
      {
        key: "financial_status",
        label: "Situação Financeira",
        description: "Regularizada, Pendente, Com Dívidas",
        type: "select",
        options: ["Regularizada", "Pendente", "Com Dívidas"],
        required: false,
        example: "Regularizada",
        aliases: ["situacao financeira", "estado financeiro", "status financeiro"],
      },
    ],
  },
};

function stripStopWords(text: string): string {
  return text.replace(/\b(de|do|da|dos|das|no|na)\b/g, "").replace(/\s+/g, " ").trim();
}

/**
 * Encontra a melhor correspondência de coluna com base nos aliases do catálogo.
 */
export function findCatalogMatch(
  header: string,
  moduleCatalog: ModuleFieldCatalog,
): { field: FieldDefinition; confidence: number } | null {
  const normHeader = foldForCompare(header);
  if (!normHeader) return null;
  const strippedHeader = stripStopWords(normHeader);

  for (const field of moduleCatalog.fields) {
    const normKey = foldForCompare(field.key);
    const normLabel = foldForCompare(field.label);

    // Correspondência exata de key ou label
    if (normHeader === normKey || normHeader === normLabel) {
      return { field, confidence: 1.0 };
    }

    // Correspondência exata com algum alias
    for (const alias of field.aliases) {
      const normAlias = foldForCompare(alias);
      if (normHeader === normAlias || strippedHeader === stripStopWords(normAlias)) {
        return { field, confidence: 0.95 };
      }
    }

    // Correspondência parcial (inclusão de substring)
    for (const alias of field.aliases) {
      const normAlias = foldForCompare(alias);
      if (normHeader.includes(normAlias) || normAlias.includes(normHeader)) {
        return { field, confidence: 0.75 };
      }
    }
  }

  return null;
}
